var annotated_dup =
[
    [ "nlohmann", "namespacenlohmann.html", [
      [ "detail", "namespacenlohmann_1_1detail.html", [
        [ "container_input_adapter_factory_impl", "namespacenlohmann_1_1detail_1_1container__input__adapter__factory__impl.html", [
          [ "container_input_adapter_factory", "structnlohmann_1_1detail_1_1container__input__adapter__factory__impl_1_1container__input__adapter__factory.html", null ],
          [ "container_input_adapter_factory< ContainerType, void_t< decltype(begin(std::declval< ContainerType >()), end(std::declval< ContainerType >()))> >", "structnlohmann_1_1detail_1_1container__input__adapter__factory__impl_1_1container__input__adapte602516bdb0b70b8ee5c6d4ff825368be.html", "structnlohmann_1_1detail_1_1container__input__adapter__factory__impl_1_1container__input__adapte602516bdb0b70b8ee5c6d4ff825368be" ]
        ] ],
        [ "dtoa_impl", "namespacenlohmann_1_1detail_1_1dtoa__impl.html", [
          [ "boundaries", "structnlohmann_1_1detail_1_1dtoa__impl_1_1boundaries.html", "structnlohmann_1_1detail_1_1dtoa__impl_1_1boundaries" ],
          [ "cached_power", "structnlohmann_1_1detail_1_1dtoa__impl_1_1cached__power.html", "structnlohmann_1_1detail_1_1dtoa__impl_1_1cached__power" ],
          [ "diyfp", "structnlohmann_1_1detail_1_1dtoa__impl_1_1diyfp.html", "structnlohmann_1_1detail_1_1dtoa__impl_1_1diyfp" ]
        ] ],
        [ "utility_internal", "namespacenlohmann_1_1detail_1_1utility__internal.html", [
          [ "Extend", "structnlohmann_1_1detail_1_1utility__internal_1_1Extend.html", null ],
          [ "Extend< integer_sequence< T, Ints... >, SeqSize, 0 >", "structnlohmann_1_1detail_1_1utility__internal_1_1Extend_3_01integer__sequence_3_01T_00_01Ints_8_453fbce128d545e87778192b2e607842.html", "structnlohmann_1_1detail_1_1utility__internal_1_1Extend_3_01integer__sequence_3_01T_00_01Ints_8_453fbce128d545e87778192b2e607842" ],
          [ "Extend< integer_sequence< T, Ints... >, SeqSize, 1 >", "structnlohmann_1_1detail_1_1utility__internal_1_1Extend_3_01integer__sequence_3_01T_00_01Ints_8_011635d85b816e1c1a7e948fa832c519.html", "structnlohmann_1_1detail_1_1utility__internal_1_1Extend_3_01integer__sequence_3_01T_00_01Ints_8_011635d85b816e1c1a7e948fa832c519" ],
          [ "Gen", "structnlohmann_1_1detail_1_1utility__internal_1_1Gen.html", "structnlohmann_1_1detail_1_1utility__internal_1_1Gen" ],
          [ "Gen< T, 0 >", "structnlohmann_1_1detail_1_1utility__internal_1_1Gen_3_01T_00_010_01_4.html", "structnlohmann_1_1detail_1_1utility__internal_1_1Gen_3_01T_00_010_01_4" ]
        ] ],
        [ "binary_reader", "classnlohmann_1_1detail_1_1binary__reader.html", "classnlohmann_1_1detail_1_1binary__reader" ],
        [ "binary_writer", "classnlohmann_1_1detail_1_1binary__writer.html", "classnlohmann_1_1detail_1_1binary__writer" ],
        [ "conjunction", "structnlohmann_1_1detail_1_1conjunction.html", null ],
        [ "conjunction< B1 >", "structnlohmann_1_1detail_1_1conjunction_3_01B1_01_4.html", null ],
        [ "conjunction< B1, Bn... >", "structnlohmann_1_1detail_1_1conjunction_3_01B1_00_01Bn_8_8_8_01_4.html", null ],
        [ "detector", "structnlohmann_1_1detail_1_1detector.html", "structnlohmann_1_1detail_1_1detector" ],
        [ "detector< Default, void_t< Op< Args... > >, Op, Args... >", "structnlohmann_1_1detail_1_1detector_3_01Default_00_01void__t_3_01Op_3_01Args_8_8_8_01_4_01_4_00_01Op_00_01Args_8_8_8_01_4.html", "structnlohmann_1_1detail_1_1detector_3_01Default_00_01void__t_3_01Op_3_01Args_8_8_8_01_4_01_4_00_01Op_00_01Args_8_8_8_01_4" ],
        [ "exception", "classnlohmann_1_1detail_1_1exception.html", "classnlohmann_1_1detail_1_1exception" ],
        [ "external_constructor", "structnlohmann_1_1detail_1_1external__constructor.html", null ],
        [ "external_constructor< value_t::array >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1array_01_4.html", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1array_01_4" ],
        [ "external_constructor< value_t::binary >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1binary_01_4.html", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1binary_01_4" ],
        [ "external_constructor< value_t::boolean >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1boolean_01_4.html", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1boolean_01_4" ],
        [ "external_constructor< value_t::number_float >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__float_01_4.html", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__float_01_4" ],
        [ "external_constructor< value_t::number_integer >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__integer_01_4.html", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__integer_01_4" ],
        [ "external_constructor< value_t::number_unsigned >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__unsigned_01_4.html", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__unsigned_01_4" ],
        [ "external_constructor< value_t::object >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1object_01_4.html", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1object_01_4" ],
        [ "external_constructor< value_t::string >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1string_01_4.html", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1string_01_4" ],
        [ "file_input_adapter", "classnlohmann_1_1detail_1_1file__input__adapter.html", "classnlohmann_1_1detail_1_1file__input__adapter" ],
        [ "from_json_fn", "structnlohmann_1_1detail_1_1from__json__fn.html", "structnlohmann_1_1detail_1_1from__json__fn" ],
        [ "has_from_json", "structnlohmann_1_1detail_1_1has__from__json.html", null ],
        [ "has_from_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "structnlohmann_1_1detail_1_1has__from__json_3_01BasicJsonType_00_01T_00_01enable__if__t_3_01_9is3ee028c64c76c768be45996bb13fc9c5.html", "structnlohmann_1_1detail_1_1has__from__json_3_01BasicJsonType_00_01T_00_01enable__if__t_3_01_9is3ee028c64c76c768be45996bb13fc9c5" ],
        [ "has_non_default_from_json", "structnlohmann_1_1detail_1_1has__non__default__from__json.html", null ],
        [ "has_non_default_from_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "structnlohmann_1_1detail_1_1has__non__default__from__json_3_01BasicJsonType_00_01T_00_01enable__b7a8cd863889b54d1139b207b4233111.html", "structnlohmann_1_1detail_1_1has__non__default__from__json_3_01BasicJsonType_00_01T_00_01enable__b7a8cd863889b54d1139b207b4233111" ],
        [ "has_to_json", "structnlohmann_1_1detail_1_1has__to__json.html", null ],
        [ "has_to_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "structnlohmann_1_1detail_1_1has__to__json_3_01BasicJsonType_00_01T_00_01enable__if__t_3_01_9is__4a8838c1c30336126696a126041e661c.html", "structnlohmann_1_1detail_1_1has__to__json_3_01BasicJsonType_00_01T_00_01enable__if__t_3_01_9is__4a8838c1c30336126696a126041e661c" ],
        [ "identity_tag", "structnlohmann_1_1detail_1_1identity__tag.html", null ],
        [ "input_stream_adapter", "classnlohmann_1_1detail_1_1input__stream__adapter.html", "classnlohmann_1_1detail_1_1input__stream__adapter" ],
        [ "integer_sequence", "structnlohmann_1_1detail_1_1integer__sequence.html", "structnlohmann_1_1detail_1_1integer__sequence" ],
        [ "internal_iterator", "structnlohmann_1_1detail_1_1internal__iterator.html", "structnlohmann_1_1detail_1_1internal__iterator" ],
        [ "invalid_iterator", "classnlohmann_1_1detail_1_1invalid__iterator.html", "classnlohmann_1_1detail_1_1invalid__iterator" ],
        [ "is_basic_json", "structnlohmann_1_1detail_1_1is__basic__json.html", null ],
        [ "is_basic_json< NLOHMANN_BASIC_JSON_TPL >", "structnlohmann_1_1detail_1_1is__basic__json_3_01NLOHMANN__BASIC__JSON__TPL_01_4.html", null ],
        [ "is_compatible_array_type", "structnlohmann_1_1detail_1_1is__compatible__array__type.html", null ],
        [ "is_compatible_array_type_impl", "structnlohmann_1_1detail_1_1is__compatible__array__type__impl.html", null ],
        [ "is_compatible_array_type_impl< BasicJsonType, CompatibleArrayType, enable_if_t< is_detected< iterator_t, CompatibleArrayType >::value &&is_iterator_traits< iterator_traits< detected_t< iterator_t, CompatibleArrayType > > >::value &&!std::is_same< CompatibleArrayType, detected_t< range_value_t, CompatibleArrayType > >::value > >", "structnlohmann_1_1detail_1_1is__compatible__array__type__impl_3_01BasicJsonType_00_01CompatibleAfaa3c0bd038fd031f5ee109e19639e03.html", "structnlohmann_1_1detail_1_1is__compatible__array__type__impl_3_01BasicJsonType_00_01CompatibleAfaa3c0bd038fd031f5ee109e19639e03" ],
        [ "is_compatible_integer_type", "structnlohmann_1_1detail_1_1is__compatible__integer__type.html", null ],
        [ "is_compatible_integer_type_impl", "structnlohmann_1_1detail_1_1is__compatible__integer__type__impl.html", null ],
        [ "is_compatible_integer_type_impl< RealIntegerType, CompatibleNumberIntegerType, enable_if_t< std::is_integral< RealIntegerType >::value &&std::is_integral< CompatibleNumberIntegerType >::value &&!std::is_same< bool, CompatibleNumberIntegerType >::value > >", "structnlohmann_1_1detail_1_1is__compatible__integer__type__impl_3_01RealIntegerType_00_01Compatie5920c849e839ebb9f8c57349c900796.html", "structnlohmann_1_1detail_1_1is__compatible__integer__type__impl_3_01RealIntegerType_00_01Compatie5920c849e839ebb9f8c57349c900796" ],
        [ "is_compatible_object_type", "structnlohmann_1_1detail_1_1is__compatible__object__type.html", null ],
        [ "is_compatible_object_type_impl", "structnlohmann_1_1detail_1_1is__compatible__object__type__impl.html", null ],
        [ "is_compatible_object_type_impl< BasicJsonType, CompatibleObjectType, enable_if_t< is_detected< mapped_type_t, CompatibleObjectType >::value &&is_detected< key_type_t, CompatibleObjectType >::value > >", "structnlohmann_1_1detail_1_1is__compatible__object__type__impl_3_01BasicJsonType_00_01Compatible1dd1bd23ba0e4ce33237aa702f8058a9.html", "structnlohmann_1_1detail_1_1is__compatible__object__type__impl_3_01BasicJsonType_00_01Compatible1dd1bd23ba0e4ce33237aa702f8058a9" ],
        [ "is_compatible_string_type", "structnlohmann_1_1detail_1_1is__compatible__string__type.html", "structnlohmann_1_1detail_1_1is__compatible__string__type" ],
        [ "is_compatible_type", "structnlohmann_1_1detail_1_1is__compatible__type.html", null ],
        [ "is_compatible_type_impl", "structnlohmann_1_1detail_1_1is__compatible__type__impl.html", null ],
        [ "is_compatible_type_impl< BasicJsonType, CompatibleType, enable_if_t< is_complete_type< CompatibleType >::value > >", "structnlohmann_1_1detail_1_1is__compatible__type__impl_3_01BasicJsonType_00_01CompatibleType_00_fa54cb60e66f5c6ba93b1dd3f418b703.html", "structnlohmann_1_1detail_1_1is__compatible__type__impl_3_01BasicJsonType_00_01CompatibleType_00_fa54cb60e66f5c6ba93b1dd3f418b703" ],
        [ "is_complete_type", "structnlohmann_1_1detail_1_1is__complete__type.html", null ],
        [ "is_complete_type< T, decltype(void(sizeof(T)))>", "structnlohmann_1_1detail_1_1is__complete__type_3_01T_00_01decltype_07void_07sizeof_07T_08_08_08_4.html", null ],
        [ "is_constructible", "structnlohmann_1_1detail_1_1is__constructible.html", null ],
        [ "is_constructible< const std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__constructible_3_01const_01std_1_1pair_3_01T1_00_01T2_01_4_01_4.html", null ],
        [ "is_constructible< const std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__constructible_3_01const_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", null ],
        [ "is_constructible< std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__constructible_3_01std_1_1pair_3_01T1_00_01T2_01_4_01_4.html", null ],
        [ "is_constructible< std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__constructible_3_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", null ],
        [ "is_constructible_array_type", "structnlohmann_1_1detail_1_1is__constructible__array__type.html", null ],
        [ "is_constructible_array_type_impl", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl.html", null ],
        [ "is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< !std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value &&!is_compatible_string_type< BasicJsonType, ConstructibleArrayType >::value &&is_default_constructible< ConstructibleArrayType >::value &&(std::is_move_assignable< ConstructibleArrayType >::value||std::is_copy_assignable< ConstructibleArrayType >::value)&&is_detected< iterator_t, ConstructibleArrayType >::value &&is_iterator_traits< iterator_traits< detected_t< iterator_t, ConstructibleArrayType > > >::value &&is_detected< range_value_t, ConstructibleArrayType >::value &&!std::is_same< ConstructibleArrayType, detected_t< range_value_t, ConstructibleArrayType > >::value &&is_complete_type< detected_t< range_value_t, ConstructibleArrayType > >::value > >", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl_3_01BasicJsonType_00_01Construc9fb32d79d2f03f291695c23371cb431d.html", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl_3_01BasicJsonType_00_01Construc9fb32d79d2f03f291695c23371cb431d" ],
        [ "is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value > >", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl_3_01BasicJsonType_00_01Construce6fa33688da703b95649da4749cdeb98.html", null ],
        [ "is_constructible_object_type", "structnlohmann_1_1detail_1_1is__constructible__object__type.html", null ],
        [ "is_constructible_object_type_impl", "structnlohmann_1_1detail_1_1is__constructible__object__type__impl.html", null ],
        [ "is_constructible_object_type_impl< BasicJsonType, ConstructibleObjectType, enable_if_t< is_detected< mapped_type_t, ConstructibleObjectType >::value &&is_detected< key_type_t, ConstructibleObjectType >::value > >", "structnlohmann_1_1detail_1_1is__constructible__object__type__impl_3_01BasicJsonType_00_01Construa4d1e16800f2c4963485512ecf18377c.html", "structnlohmann_1_1detail_1_1is__constructible__object__type__impl_3_01BasicJsonType_00_01Construa4d1e16800f2c4963485512ecf18377c" ],
        [ "is_constructible_string_type", "structnlohmann_1_1detail_1_1is__constructible__string__type.html", "structnlohmann_1_1detail_1_1is__constructible__string__type" ],
        [ "is_constructible_tuple", "structnlohmann_1_1detail_1_1is__constructible__tuple.html", null ],
        [ "is_constructible_tuple< T1, std::tuple< Args... > >", "structnlohmann_1_1detail_1_1is__constructible__tuple_3_01T1_00_01std_1_1tuple_3_01Args_8_8_8_01_4_01_4.html", null ],
        [ "is_default_constructible", "structnlohmann_1_1detail_1_1is__default__constructible.html", null ],
        [ "is_default_constructible< const std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01const_01std_1_1pair_3_01T1_00_01T2_01_4_01_4.html", null ],
        [ "is_default_constructible< const std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01const_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", null ],
        [ "is_default_constructible< std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01std_1_1pair_3_01T1_00_01T2_01_4_01_4.html", null ],
        [ "is_default_constructible< std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", null ],
        [ "is_detected_lazy", "structnlohmann_1_1detail_1_1is__detected__lazy.html", null ],
        [ "is_getable", "structnlohmann_1_1detail_1_1is__getable.html", "structnlohmann_1_1detail_1_1is__getable" ],
        [ "is_iterator_of_multibyte", "structnlohmann_1_1detail_1_1is__iterator__of__multibyte.html", "structnlohmann_1_1detail_1_1is__iterator__of__multibyte" ],
        [ "is_iterator_traits", "structnlohmann_1_1detail_1_1is__iterator__traits.html", null ],
        [ "is_iterator_traits< iterator_traits< T > >", "structnlohmann_1_1detail_1_1is__iterator__traits_3_01iterator__traits_3_01T_01_4_01_4.html", "structnlohmann_1_1detail_1_1is__iterator__traits_3_01iterator__traits_3_01T_01_4_01_4" ],
        [ "is_json_ref", "structnlohmann_1_1detail_1_1is__json__ref.html", null ],
        [ "is_json_ref< json_ref< T > >", "structnlohmann_1_1detail_1_1is__json__ref_3_01json__ref_3_01T_01_4_01_4.html", null ],
        [ "is_ordered_map", "structnlohmann_1_1detail_1_1is__ordered__map.html", "structnlohmann_1_1detail_1_1is__ordered__map" ],
        [ "is_range", "structnlohmann_1_1detail_1_1is__range.html", "structnlohmann_1_1detail_1_1is__range" ],
        [ "is_sax", "structnlohmann_1_1detail_1_1is__sax.html", "structnlohmann_1_1detail_1_1is__sax" ],
        [ "is_sax_static_asserts", "structnlohmann_1_1detail_1_1is__sax__static__asserts.html", "structnlohmann_1_1detail_1_1is__sax__static__asserts" ],
        [ "iter_impl", "classnlohmann_1_1detail_1_1iter__impl.html", "classnlohmann_1_1detail_1_1iter__impl" ],
        [ "iteration_proxy", "classnlohmann_1_1detail_1_1iteration__proxy.html", "classnlohmann_1_1detail_1_1iteration__proxy" ],
        [ "iteration_proxy_value", "classnlohmann_1_1detail_1_1iteration__proxy__value.html", "classnlohmann_1_1detail_1_1iteration__proxy__value" ],
        [ "iterator_input_adapter", "classnlohmann_1_1detail_1_1iterator__input__adapter.html", "classnlohmann_1_1detail_1_1iterator__input__adapter" ],
        [ "iterator_input_adapter_factory", "structnlohmann_1_1detail_1_1iterator__input__adapter__factory.html", "structnlohmann_1_1detail_1_1iterator__input__adapter__factory" ],
        [ "iterator_input_adapter_factory< IteratorType, enable_if_t< is_iterator_of_multibyte< IteratorType >::value > >", "structnlohmann_1_1detail_1_1iterator__input__adapter__factory_3_01IteratorType_00_01enable__if__0e86378a778d78dd2284e92dc30f4902.html", "structnlohmann_1_1detail_1_1iterator__input__adapter__factory_3_01IteratorType_00_01enable__if__0e86378a778d78dd2284e92dc30f4902" ],
        [ "iterator_traits", "structnlohmann_1_1detail_1_1iterator__traits.html", null ],
        [ "iterator_traits< T *, enable_if_t< std::is_object< T >::value > >", "structnlohmann_1_1detail_1_1iterator__traits_3_01T_01_5_00_01enable__if__t_3_01std_1_1is__object_3_01T_01_4_1_1value_01_4_01_4.html", "structnlohmann_1_1detail_1_1iterator__traits_3_01T_01_5_00_01enable__if__t_3_01std_1_1is__object_3_01T_01_4_1_1value_01_4_01_4" ],
        [ "iterator_traits< T, enable_if_t< !std::is_pointer< T >::value > >", "structnlohmann_1_1detail_1_1iterator__traits_3_01T_00_01enable__if__t_3_01_9std_1_1is__pointer_3_01T_01_4_1_1value_01_4_01_4.html", null ],
        [ "iterator_types", "structnlohmann_1_1detail_1_1iterator__types.html", null ],
        [ "iterator_types< It, void_t< typename It::difference_type, typename It::value_type, typename It::pointer, typename It::reference, typename It::iterator_category > >", "structnlohmann_1_1detail_1_1iterator__types_3_01It_00_01void__t_3_01typename_01It_1_1difference_d2be8685966c97e00e99d4fd2366dc0b.html", "structnlohmann_1_1detail_1_1iterator__types_3_01It_00_01void__t_3_01typename_01It_1_1difference_d2be8685966c97e00e99d4fd2366dc0b" ],
        [ "json_ref", "classnlohmann_1_1detail_1_1json__ref.html", "classnlohmann_1_1detail_1_1json__ref" ],
        [ "json_reverse_iterator", "classnlohmann_1_1detail_1_1json__reverse__iterator.html", "classnlohmann_1_1detail_1_1json__reverse__iterator" ],
        [ "json_sax_acceptor", "classnlohmann_1_1detail_1_1json__sax__acceptor.html", "classnlohmann_1_1detail_1_1json__sax__acceptor" ],
        [ "json_sax_dom_callback_parser", "classnlohmann_1_1detail_1_1json__sax__dom__callback__parser.html", "classnlohmann_1_1detail_1_1json__sax__dom__callback__parser" ],
        [ "json_sax_dom_parser", "classnlohmann_1_1detail_1_1json__sax__dom__parser.html", "classnlohmann_1_1detail_1_1json__sax__dom__parser" ],
        [ "lexer", "classnlohmann_1_1detail_1_1lexer.html", "classnlohmann_1_1detail_1_1lexer" ],
        [ "lexer_base", "classnlohmann_1_1detail_1_1lexer__base.html", "classnlohmann_1_1detail_1_1lexer__base" ],
        [ "make_void", "structnlohmann_1_1detail_1_1make__void.html", "structnlohmann_1_1detail_1_1make__void" ],
        [ "negation", "structnlohmann_1_1detail_1_1negation.html", null ],
        [ "nonesuch", "structnlohmann_1_1detail_1_1nonesuch.html", "structnlohmann_1_1detail_1_1nonesuch" ],
        [ "other_error", "classnlohmann_1_1detail_1_1other__error.html", "classnlohmann_1_1detail_1_1other__error" ],
        [ "out_of_range", "classnlohmann_1_1detail_1_1out__of__range.html", "classnlohmann_1_1detail_1_1out__of__range" ],
        [ "output_adapter", "classnlohmann_1_1detail_1_1output__adapter.html", "classnlohmann_1_1detail_1_1output__adapter" ],
        [ "output_adapter_protocol", "structnlohmann_1_1detail_1_1output__adapter__protocol.html", "structnlohmann_1_1detail_1_1output__adapter__protocol" ],
        [ "output_stream_adapter", "classnlohmann_1_1detail_1_1output__stream__adapter.html", "classnlohmann_1_1detail_1_1output__stream__adapter" ],
        [ "output_string_adapter", "classnlohmann_1_1detail_1_1output__string__adapter.html", "classnlohmann_1_1detail_1_1output__string__adapter" ],
        [ "output_vector_adapter", "classnlohmann_1_1detail_1_1output__vector__adapter.html", "classnlohmann_1_1detail_1_1output__vector__adapter" ],
        [ "parse_error", "classnlohmann_1_1detail_1_1parse__error.html", "classnlohmann_1_1detail_1_1parse__error" ],
        [ "parser", "classnlohmann_1_1detail_1_1parser.html", "classnlohmann_1_1detail_1_1parser" ],
        [ "position_t", "structnlohmann_1_1detail_1_1position__t.html", "structnlohmann_1_1detail_1_1position__t" ],
        [ "primitive_iterator_t", "classnlohmann_1_1detail_1_1primitive__iterator__t.html", "classnlohmann_1_1detail_1_1primitive__iterator__t" ],
        [ "priority_tag", "structnlohmann_1_1detail_1_1priority__tag.html", null ],
        [ "priority_tag< 0 >", "structnlohmann_1_1detail_1_1priority__tag_3_010_01_4.html", null ],
        [ "serializer", "classnlohmann_1_1detail_1_1serializer.html", "classnlohmann_1_1detail_1_1serializer" ],
        [ "span_input_adapter", "classnlohmann_1_1detail_1_1span__input__adapter.html", "classnlohmann_1_1detail_1_1span__input__adapter" ],
        [ "static_const", "structnlohmann_1_1detail_1_1static__const.html", "structnlohmann_1_1detail_1_1static__const" ],
        [ "to_json_fn", "structnlohmann_1_1detail_1_1to__json__fn.html", "structnlohmann_1_1detail_1_1to__json__fn" ],
        [ "type_error", "classnlohmann_1_1detail_1_1type__error.html", "classnlohmann_1_1detail_1_1type__error" ],
        [ "wide_string_input_adapter", "classnlohmann_1_1detail_1_1wide__string__input__adapter.html", "classnlohmann_1_1detail_1_1wide__string__input__adapter" ],
        [ "wide_string_input_helper", "structnlohmann_1_1detail_1_1wide__string__input__helper.html", null ],
        [ "wide_string_input_helper< BaseInputAdapter, 2 >", "structnlohmann_1_1detail_1_1wide__string__input__helper_3_01BaseInputAdapter_00_012_01_4.html", "structnlohmann_1_1detail_1_1wide__string__input__helper_3_01BaseInputAdapter_00_012_01_4" ],
        [ "wide_string_input_helper< BaseInputAdapter, 4 >", "structnlohmann_1_1detail_1_1wide__string__input__helper_3_01BaseInputAdapter_00_014_01_4.html", "structnlohmann_1_1detail_1_1wide__string__input__helper_3_01BaseInputAdapter_00_014_01_4" ]
      ] ],
      [ "adl_serializer", "structnlohmann_1_1adl__serializer.html", "structnlohmann_1_1adl__serializer" ],
      [ "basic_json", "classnlohmann_1_1basic__json.html", "classnlohmann_1_1basic__json" ],
      [ "byte_container_with_subtype", "classnlohmann_1_1byte__container__with__subtype.html", "classnlohmann_1_1byte__container__with__subtype" ],
      [ "json_pointer", "classnlohmann_1_1json__pointer.html", "classnlohmann_1_1json__pointer" ],
      [ "json_sax", "structnlohmann_1_1json__sax.html", "structnlohmann_1_1json__sax" ],
      [ "ordered_map", "structnlohmann_1_1ordered__map.html", "structnlohmann_1_1ordered__map" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< nlohmann::json >", "structstd_1_1hash_3_01nlohmann_1_1json_01_4.html", "structstd_1_1hash_3_01nlohmann_1_1json_01_4" ],
      [ "less<::nlohmann::detail::value_t >", "structstd_1_1less_3_1_1nlohmann_1_1detail_1_1value__t_01_4.html", "structstd_1_1less_3_1_1nlohmann_1_1detail_1_1value__t_01_4" ],
      [ "tuple_element< N, ::nlohmann::detail::iteration_proxy_value< IteratorType > >", "classstd_1_1tuple__element_3_01N_00_01_1_1nlohmann_1_1detail_1_1iteration__proxy__value_3_01IteratorType_01_4_01_4.html", "classstd_1_1tuple__element_3_01N_00_01_1_1nlohmann_1_1detail_1_1iteration__proxy__value_3_01IteratorType_01_4_01_4" ],
      [ "tuple_size<::nlohmann::detail::iteration_proxy_value< IteratorType > >", "classstd_1_1tuple__size_3_1_1nlohmann_1_1detail_1_1iteration__proxy__value_3_01IteratorType_01_4_01_4.html", null ]
    ] ],
    [ "tinygltf", "namespacetinygltf.html", [
      [ "detail", "namespacetinygltf_1_1detail.html", [
        [ "CJ_NoAllocator", "structtinygltf_1_1detail_1_1CJ__NoAllocator.html", null ]
      ] ],
      [ "Accessor", "structtinygltf_1_1Accessor.html", "structtinygltf_1_1Accessor" ],
      [ "Animation", "structtinygltf_1_1Animation.html", "structtinygltf_1_1Animation" ],
      [ "AnimationChannel", "structtinygltf_1_1AnimationChannel.html", "structtinygltf_1_1AnimationChannel" ],
      [ "AnimationSampler", "structtinygltf_1_1AnimationSampler.html", "structtinygltf_1_1AnimationSampler" ],
      [ "Asset", "structtinygltf_1_1Asset.html", "structtinygltf_1_1Asset" ],
      [ "AudioEmitter", "structtinygltf_1_1AudioEmitter.html", "structtinygltf_1_1AudioEmitter" ],
      [ "AudioSource", "structtinygltf_1_1AudioSource.html", "structtinygltf_1_1AudioSource" ],
      [ "Buffer", "structtinygltf_1_1Buffer.html", "structtinygltf_1_1Buffer" ],
      [ "BufferView", "structtinygltf_1_1BufferView.html", "structtinygltf_1_1BufferView" ],
      [ "Camera", "structtinygltf_1_1Camera.html", "structtinygltf_1_1Camera" ],
      [ "FsCallbacks", "structtinygltf_1_1FsCallbacks.html", "structtinygltf_1_1FsCallbacks" ],
      [ "Image", "structtinygltf_1_1Image.html", "structtinygltf_1_1Image" ],
      [ "Light", "structtinygltf_1_1Light.html", "structtinygltf_1_1Light" ],
      [ "Material", "structtinygltf_1_1Material.html", "structtinygltf_1_1Material" ],
      [ "Mesh", "structtinygltf_1_1Mesh.html", "structtinygltf_1_1Mesh" ],
      [ "Model", "classtinygltf_1_1Model.html", "classtinygltf_1_1Model" ],
      [ "Node", "classtinygltf_1_1Node.html", "classtinygltf_1_1Node" ],
      [ "NormalTextureInfo", "structtinygltf_1_1NormalTextureInfo.html", "structtinygltf_1_1NormalTextureInfo" ],
      [ "OcclusionTextureInfo", "structtinygltf_1_1OcclusionTextureInfo.html", "structtinygltf_1_1OcclusionTextureInfo" ],
      [ "OrthographicCamera", "structtinygltf_1_1OrthographicCamera.html", "structtinygltf_1_1OrthographicCamera" ],
      [ "Parameter", "structtinygltf_1_1Parameter.html", "structtinygltf_1_1Parameter" ],
      [ "PbrMetallicRoughness", "structtinygltf_1_1PbrMetallicRoughness.html", "structtinygltf_1_1PbrMetallicRoughness" ],
      [ "PerspectiveCamera", "structtinygltf_1_1PerspectiveCamera.html", "structtinygltf_1_1PerspectiveCamera" ],
      [ "PositionalEmitter", "structtinygltf_1_1PositionalEmitter.html", "structtinygltf_1_1PositionalEmitter" ],
      [ "Primitive", "structtinygltf_1_1Primitive.html", "structtinygltf_1_1Primitive" ],
      [ "Sampler", "structtinygltf_1_1Sampler.html", "structtinygltf_1_1Sampler" ],
      [ "Scene", "structtinygltf_1_1Scene.html", "structtinygltf_1_1Scene" ],
      [ "Skin", "structtinygltf_1_1Skin.html", "structtinygltf_1_1Skin" ],
      [ "SpotLight", "structtinygltf_1_1SpotLight.html", "structtinygltf_1_1SpotLight" ],
      [ "Texture", "structtinygltf_1_1Texture.html", "structtinygltf_1_1Texture" ],
      [ "TextureInfo", "structtinygltf_1_1TextureInfo.html", "structtinygltf_1_1TextureInfo" ],
      [ "TinyGLTF", "classtinygltf_1_1TinyGLTF.html", "classtinygltf_1_1TinyGLTF" ],
      [ "URICallbacks", "structtinygltf_1_1URICallbacks.html", "structtinygltf_1_1URICallbacks" ],
      [ "Value", "classtinygltf_1_1Value.html", "classtinygltf_1_1Value" ]
    ] ],
    [ "AnimationChannelData", "structAnimationChannelData.html", "structAnimationChannelData" ],
    [ "AnimationData", "structAnimationData.html", "structAnimationData" ],
    [ "AnimationSamplerData", "structAnimationSamplerData.html", "structAnimationSamplerData" ],
    [ "Audio", "classAudio.html", "classAudio" ],
    [ "BillBoard", "classBillBoard.html", "classBillBoard" ],
    [ "BoxCollider3D", "classBoxCollider3D.html", "classBoxCollider3D" ],
    [ "Bullet", "classBullet.html", "classBullet" ],
    [ "ButtonEventManager", "classButtonEventManager.html", "classButtonEventManager" ],
    [ "C3D_Object", "classC3D__Object.html", "classC3D__Object" ],
    [ "Camera", "classCamera.html", "classCamera" ],
    [ "CBone", "classCBone.html", "classCBone" ],
    [ "CBox", "classCBox.html", "classCBox" ],
    [ "CComponent", "classCComponent.html", "classCComponent" ],
    [ "CDescriptorHeapAllocator", "classCDescriptorHeapAllocator.html", "classCDescriptorHeapAllocator" ],
    [ "CgltfLoader", "classCgltfLoader.html", null ],
    [ "CImGuiManager", "classCImGuiManager.html", "classCImGuiManager" ],
    [ "CInputManager", "classCInputManager.html", "classCInputManager" ],
    [ "CInspectorUI", "classCInspectorUI.html", "classCInspectorUI" ],
    [ "cj_frame", "structcj__frame.html", "structcj__frame" ],
    [ "cj_parse_ctx", "structcj__parse__ctx.html", "structcj__parse__ctx" ],
    [ "cj_strbuf", "structcj__strbuf.html", "structcj__strbuf" ],
    [ "CMaterial", "classCMaterial.html", "classCMaterial" ],
    [ "CMesh", "classCMesh.html", "classCMesh" ],
    [ "CModel", "classCModel.html", "classCModel" ],
    [ "CObject", "classCObject.html", "classCObject" ],
    [ "CObjectInfo", "classCObjectInfo.html", "classCObjectInfo" ],
    [ "Collider", "classCollider.html", "classCollider" ],
    [ "Collider3D", "classCollider3D.html", "classCollider3D" ],
    [ "Collision", "classCollision.html", "classCollision" ],
    [ "ConstantBufferData", "structConstantBufferData.html", "structConstantBufferData" ],
    [ "CScene", "classCScene.html", "classCScene" ],
    [ "CSceneTest", "classCSceneTest.html", "classCSceneTest" ],
    [ "CSpriteRenderer", "classCSpriteRenderer.html", "classCSpriteRenderer" ],
    [ "CTextRenderer", "classCTextRenderer.html", "classCTextRenderer" ],
    [ "CTexture", "classCTexture.html", "classCTexture" ],
    [ "CTransform", "classCTransform.html", "classCTransform" ],
    [ "CUIButton", "classCUIButton.html", "classCUIButton" ],
    [ "CUIObject", "classCUIObject.html", "classCUIObject" ],
    [ "D2DTextRenderer", "classD2DTextRenderer.html", "classD2DTextRenderer" ],
    [ "DX12Manager", "classDX12Manager.html", "classDX12Manager" ],
    [ "Enemy", "classEnemy.html", "classEnemy" ],
    [ "EnemyCount", "classEnemyCount.html", "classEnemyCount" ],
    [ "EnemyCounter", "classEnemyCounter.html", "classEnemyCounter" ],
    [ "Event", "classEvent.html", "classEvent" ],
    [ "EventData", "classEventData.html", "classEventData" ],
    [ "EventData_NextScene", "classEventData__NextScene.html", "classEventData__NextScene" ],
    [ "EventManager", "classEventManager.html", "classEventManager" ],
    [ "ExampleAppConsole", "structExampleAppConsole.html", "structExampleAppConsole" ],
    [ "ExampleAppDocuments", "structExampleAppDocuments.html", "structExampleAppDocuments" ],
    [ "ExampleAppLog", "structExampleAppLog.html", "structExampleAppLog" ],
    [ "ExampleAppPropertyEditor", "structExampleAppPropertyEditor.html", "structExampleAppPropertyEditor" ],
    [ "ExampleAsset", "structExampleAsset.html", "structExampleAsset" ],
    [ "ExampleAssetsBrowser", "structExampleAssetsBrowser.html", "structExampleAssetsBrowser" ],
    [ "ExampleDualListBox", "structExampleDualListBox.html", "structExampleDualListBox" ],
    [ "ExampleMemberInfo", "structExampleMemberInfo.html", "structExampleMemberInfo" ],
    [ "ExampleSelectionWithDeletion", "structExampleSelectionWithDeletion.html", "structExampleSelectionWithDeletion" ],
    [ "ExampleTreeNode", "structExampleTreeNode.html", "structExampleTreeNode" ],
    [ "Explosion", "classExplosion.html", "classExplosion" ],
    [ "ForwardRenderPass", "classForwardRenderPass.html", "classForwardRenderPass" ],
    [ "ImBitArray", "structImBitArray.html", "structImBitArray" ],
    [ "ImBitVector", "structImBitVector.html", "structImBitVector" ],
    [ "ImChunkStream", "structImChunkStream.html", "structImChunkStream" ],
    [ "ImColor", "structImColor.html", "structImColor" ],
    [ "ImDrawChannel", "structImDrawChannel.html", "structImDrawChannel" ],
    [ "ImDrawCmd", "structImDrawCmd.html", "structImDrawCmd" ],
    [ "ImDrawCmdHeader", "structImDrawCmdHeader.html", "structImDrawCmdHeader" ],
    [ "ImDrawData", "structImDrawData.html", "structImDrawData" ],
    [ "ImDrawDataBuilder", "structImDrawDataBuilder.html", "structImDrawDataBuilder" ],
    [ "ImDrawList", "structImDrawList.html", "structImDrawList" ],
    [ "ImDrawListSharedData", "structImDrawListSharedData.html", "structImDrawListSharedData" ],
    [ "ImDrawListSplitter", "structImDrawListSplitter.html", "structImDrawListSplitter" ],
    [ "ImDrawVert", "structImDrawVert.html", "structImDrawVert" ],
    [ "ImFont", "structImFont.html", "structImFont" ],
    [ "ImFontAtlas", "structImFontAtlas.html", "structImFontAtlas" ],
    [ "ImFontAtlasBuilder", "structImFontAtlasBuilder.html", "structImFontAtlasBuilder" ],
    [ "ImFontAtlasPostProcessData", "structImFontAtlasPostProcessData.html", "structImFontAtlasPostProcessData" ],
    [ "ImFontAtlasRect", "structImFontAtlasRect.html", "structImFontAtlasRect" ],
    [ "ImFontAtlasRectEntry", "structImFontAtlasRectEntry.html", "structImFontAtlasRectEntry" ],
    [ "ImFontBaked", "structImFontBaked.html", "structImFontBaked" ],
    [ "ImFontConfig", "structImFontConfig.html", "structImFontConfig" ],
    [ "ImFontGlyph", "structImFontGlyph.html", "structImFontGlyph" ],
    [ "ImFontGlyphRangesBuilder", "structImFontGlyphRangesBuilder.html", "structImFontGlyphRangesBuilder" ],
    [ "ImFontLoader", "structImFontLoader.html", "structImFontLoader" ],
    [ "ImFontStackData", "structImFontStackData.html", "structImFontStackData" ],
    [ "ImGui_ImplDX12_Data", "structImGui__ImplDX12__Data.html", "structImGui__ImplDX12__Data" ],
    [ "ImGui_ImplDX12_InitInfo", "structImGui__ImplDX12__InitInfo.html", "structImGui__ImplDX12__InitInfo" ],
    [ "ImGui_ImplDX12_RenderBuffers", "structImGui__ImplDX12__RenderBuffers.html", "structImGui__ImplDX12__RenderBuffers" ],
    [ "ImGui_ImplDX12_RenderState", "structImGui__ImplDX12__RenderState.html", "structImGui__ImplDX12__RenderState" ],
    [ "ImGui_ImplDX12_Texture", "structImGui__ImplDX12__Texture.html", "structImGui__ImplDX12__Texture" ],
    [ "ImGui_ImplStbTrueType_FontSrcData", "structImGui__ImplStbTrueType__FontSrcData.html", "structImGui__ImplStbTrueType__FontSrcData" ],
    [ "ImGui_ImplWin32_Data", "structImGui__ImplWin32__Data.html", "structImGui__ImplWin32__Data" ],
    [ "ImGuiBoxSelectState", "structImGuiBoxSelectState.html", "structImGuiBoxSelectState" ],
    [ "ImGuiColorMod", "structImGuiColorMod.html", "structImGuiColorMod" ],
    [ "ImGuiComboPreviewData", "structImGuiComboPreviewData.html", "structImGuiComboPreviewData" ],
    [ "ImGuiContext", "structImGuiContext.html", "structImGuiContext" ],
    [ "ImGuiContextHook", "structImGuiContextHook.html", "structImGuiContextHook" ],
    [ "ImGuiDataTypeInfo", "structImGuiDataTypeInfo.html", "structImGuiDataTypeInfo" ],
    [ "ImGuiDataTypeStorage", "structImGuiDataTypeStorage.html", "structImGuiDataTypeStorage" ],
    [ "ImGuiDeactivatedItemData", "structImGuiDeactivatedItemData.html", "structImGuiDeactivatedItemData" ],
    [ "ImGuiDebugAllocEntry", "structImGuiDebugAllocEntry.html", "structImGuiDebugAllocEntry" ],
    [ "ImGuiDebugAllocInfo", "structImGuiDebugAllocInfo.html", "structImGuiDebugAllocInfo" ],
    [ "ImGuiDebugItemPathQuery", "structImGuiDebugItemPathQuery.html", "structImGuiDebugItemPathQuery" ],
    [ "ImGuiDemoWindowData", "structImGuiDemoWindowData.html", "structImGuiDemoWindowData" ],
    [ "ImGuiErrorRecoveryState", "structImGuiErrorRecoveryState.html", "structImGuiErrorRecoveryState" ],
    [ "ImGuiFocusScopeData", "structImGuiFocusScopeData.html", "structImGuiFocusScopeData" ],
    [ "ImGuiGroupData", "structImGuiGroupData.html", "structImGuiGroupData" ],
    [ "ImGuiIDStackTool", "structImGuiIDStackTool.html", "structImGuiIDStackTool" ],
    [ "ImGuiInputEvent", "structImGuiInputEvent.html", "structImGuiInputEvent" ],
    [ "ImGuiInputEventAppFocused", "structImGuiInputEventAppFocused.html", "structImGuiInputEventAppFocused" ],
    [ "ImGuiInputEventKey", "structImGuiInputEventKey.html", "structImGuiInputEventKey" ],
    [ "ImGuiInputEventMouseButton", "structImGuiInputEventMouseButton.html", "structImGuiInputEventMouseButton" ],
    [ "ImGuiInputEventMousePos", "structImGuiInputEventMousePos.html", "structImGuiInputEventMousePos" ],
    [ "ImGuiInputEventMouseWheel", "structImGuiInputEventMouseWheel.html", "structImGuiInputEventMouseWheel" ],
    [ "ImGuiInputEventText", "structImGuiInputEventText.html", "structImGuiInputEventText" ],
    [ "ImGuiInputTextCallbackData", "structImGuiInputTextCallbackData.html", "structImGuiInputTextCallbackData" ],
    [ "ImGuiInputTextDeactivatedState", "structImGuiInputTextDeactivatedState.html", "structImGuiInputTextDeactivatedState" ],
    [ "ImGuiInputTextState", "structImGuiInputTextState.html", "structImGuiInputTextState" ],
    [ "ImGuiIO", "structImGuiIO.html", "structImGuiIO" ],
    [ "ImGuiKeyData", "structImGuiKeyData.html", "structImGuiKeyData" ],
    [ "ImGuiKeyOwnerData", "structImGuiKeyOwnerData.html", "structImGuiKeyOwnerData" ],
    [ "ImGuiKeyRoutingData", "structImGuiKeyRoutingData.html", "structImGuiKeyRoutingData" ],
    [ "ImGuiKeyRoutingTable", "structImGuiKeyRoutingTable.html", "structImGuiKeyRoutingTable" ],
    [ "ImGuiLastItemData", "structImGuiLastItemData.html", "structImGuiLastItemData" ],
    [ "ImGuiListClipper", "structImGuiListClipper.html", "structImGuiListClipper" ],
    [ "ImGuiListClipperData", "structImGuiListClipperData.html", "structImGuiListClipperData" ],
    [ "ImGuiListClipperRange", "structImGuiListClipperRange.html", "structImGuiListClipperRange" ],
    [ "ImGuiLocEntry", "structImGuiLocEntry.html", "structImGuiLocEntry" ],
    [ "ImGuiMenuColumns", "structImGuiMenuColumns.html", "structImGuiMenuColumns" ],
    [ "ImGuiMetricsConfig", "structImGuiMetricsConfig.html", "structImGuiMetricsConfig" ],
    [ "ImGuiMultiSelectIO", "structImGuiMultiSelectIO.html", "structImGuiMultiSelectIO" ],
    [ "ImGuiMultiSelectState", "structImGuiMultiSelectState.html", "structImGuiMultiSelectState" ],
    [ "ImGuiMultiSelectTempData", "structImGuiMultiSelectTempData.html", "structImGuiMultiSelectTempData" ],
    [ "ImGuiNavItemData", "structImGuiNavItemData.html", "structImGuiNavItemData" ],
    [ "ImGuiNextItemData", "structImGuiNextItemData.html", "structImGuiNextItemData" ],
    [ "ImGuiNextWindowData", "structImGuiNextWindowData.html", "structImGuiNextWindowData" ],
    [ "ImGuiOldColumnData", "structImGuiOldColumnData.html", "structImGuiOldColumnData" ],
    [ "ImGuiOldColumns", "structImGuiOldColumns.html", "structImGuiOldColumns" ],
    [ "ImGuiOnceUponAFrame", "structImGuiOnceUponAFrame.html", "structImGuiOnceUponAFrame" ],
    [ "ImGuiPayload", "structImGuiPayload.html", "structImGuiPayload" ],
    [ "ImGuiPlatformImeData", "structImGuiPlatformImeData.html", "structImGuiPlatformImeData" ],
    [ "ImGuiPlatformIO", "structImGuiPlatformIO.html", "structImGuiPlatformIO" ],
    [ "ImGuiPlotArrayGetterData", "structImGuiPlotArrayGetterData.html", "structImGuiPlotArrayGetterData" ],
    [ "ImGuiPopupData", "structImGuiPopupData.html", "structImGuiPopupData" ],
    [ "ImGuiPtrOrIndex", "structImGuiPtrOrIndex.html", "structImGuiPtrOrIndex" ],
    [ "ImGuiResizeBorderDef", "structImGuiResizeBorderDef.html", "structImGuiResizeBorderDef" ],
    [ "ImGuiResizeGripDef", "structImGuiResizeGripDef.html", "structImGuiResizeGripDef" ],
    [ "ImGuiSelectionBasicStorage", "structImGuiSelectionBasicStorage.html", "structImGuiSelectionBasicStorage" ],
    [ "ImGuiSelectionExternalStorage", "structImGuiSelectionExternalStorage.html", "structImGuiSelectionExternalStorage" ],
    [ "ImGuiSelectionRequest", "structImGuiSelectionRequest.html", "structImGuiSelectionRequest" ],
    [ "ImGuiSettingsHandler", "structImGuiSettingsHandler.html", "structImGuiSettingsHandler" ],
    [ "ImGuiShrinkWidthItem", "structImGuiShrinkWidthItem.html", "structImGuiShrinkWidthItem" ],
    [ "ImGuiSizeCallbackData", "structImGuiSizeCallbackData.html", "structImGuiSizeCallbackData" ],
    [ "ImGuiStackLevelInfo", "structImGuiStackLevelInfo.html", "structImGuiStackLevelInfo" ],
    [ "ImGuiStorage", "structImGuiStorage.html", "structImGuiStorage" ],
    [ "ImGuiStoragePair", "structImGuiStoragePair.html", "structImGuiStoragePair" ],
    [ "ImGuiStyle", "structImGuiStyle.html", "structImGuiStyle" ],
    [ "ImGuiStyleMod", "structImGuiStyleMod.html", "structImGuiStyleMod" ],
    [ "ImGuiStyleVarInfo", "structImGuiStyleVarInfo.html", "structImGuiStyleVarInfo" ],
    [ "ImGuiTabBar", "structImGuiTabBar.html", "structImGuiTabBar" ],
    [ "ImGuiTabBarSection", "structImGuiTabBarSection.html", "structImGuiTabBarSection" ],
    [ "ImGuiTabItem", "structImGuiTabItem.html", "structImGuiTabItem" ],
    [ "ImGuiTable", "structImGuiTable.html", "structImGuiTable" ],
    [ "ImGuiTableCellData", "structImGuiTableCellData.html", "structImGuiTableCellData" ],
    [ "ImGuiTableColumn", "structImGuiTableColumn.html", "structImGuiTableColumn" ],
    [ "ImGuiTableColumnSettings", "structImGuiTableColumnSettings.html", "structImGuiTableColumnSettings" ],
    [ "ImGuiTableColumnSortSpecs", "structImGuiTableColumnSortSpecs.html", "structImGuiTableColumnSortSpecs" ],
    [ "ImGuiTableFixDisplayOrderColumnData", "structImGuiTableFixDisplayOrderColumnData.html", "structImGuiTableFixDisplayOrderColumnData" ],
    [ "ImGuiTableHeaderData", "structImGuiTableHeaderData.html", "structImGuiTableHeaderData" ],
    [ "ImGuiTableInstanceData", "structImGuiTableInstanceData.html", "structImGuiTableInstanceData" ],
    [ "ImGuiTableSettings", "structImGuiTableSettings.html", "structImGuiTableSettings" ],
    [ "ImGuiTableSortSpecs", "structImGuiTableSortSpecs.html", "structImGuiTableSortSpecs" ],
    [ "ImGuiTableTempData", "structImGuiTableTempData.html", "structImGuiTableTempData" ],
    [ "ImGuiTextBuffer", "structImGuiTextBuffer.html", "structImGuiTextBuffer" ],
    [ "ImGuiTextFilter", "structImGuiTextFilter.html", "structImGuiTextFilter" ],
    [ "ImGuiTextIndex", "structImGuiTextIndex.html", "structImGuiTextIndex" ],
    [ "ImGuiTreeNodeStackData", "structImGuiTreeNodeStackData.html", "structImGuiTreeNodeStackData" ],
    [ "ImGuiTypingSelectRequest", "structImGuiTypingSelectRequest.html", "structImGuiTypingSelectRequest" ],
    [ "ImGuiTypingSelectState", "structImGuiTypingSelectState.html", "structImGuiTypingSelectState" ],
    [ "ImGuiViewport", "structImGuiViewport.html", "structImGuiViewport" ],
    [ "ImGuiViewportP", "structImGuiViewportP.html", "structImGuiViewportP" ],
    [ "ImGuiWindow", "structImGuiWindow.html", "structImGuiWindow" ],
    [ "ImGuiWindowSettings", "structImGuiWindowSettings.html", "structImGuiWindowSettings" ],
    [ "ImGuiWindowStackData", "structImGuiWindowStackData.html", "structImGuiWindowStackData" ],
    [ "ImGuiWindowTempData", "structImGuiWindowTempData.html", "structImGuiWindowTempData" ],
    [ "ImNewWrapper", "structImNewWrapper.html", null ],
    [ "ImPool", "structImPool.html", "structImPool" ],
    [ "ImRect", "structImRect.html", "structImRect" ],
    [ "ImSpan", "structImSpan.html", "structImSpan" ],
    [ "ImSpanAllocator", "structImSpanAllocator.html", "structImSpanAllocator" ],
    [ "ImStableVector", "structImStableVector.html", "structImStableVector" ],
    [ "ImTextureData", "structImTextureData.html", "structImTextureData" ],
    [ "ImTextureRect", "structImTextureRect.html", "structImTextureRect" ],
    [ "ImTextureRef", "structImTextureRef.html", "structImTextureRef" ],
    [ "ImTriangulator", "structImTriangulator.html", "structImTriangulator" ],
    [ "ImTriangulatorNode", "structImTriangulatorNode.html", "structImTriangulatorNode" ],
    [ "ImTriangulatorNodeSpan", "structImTriangulatorNodeSpan.html", "structImTriangulatorNodeSpan" ],
    [ "ImVec1", "structImVec1.html", "structImVec1" ],
    [ "ImVec2", "structImVec2.html", "structImVec2" ],
    [ "ImVec2i", "structImVec2i.html", "structImVec2i" ],
    [ "ImVec2ih", "structImVec2ih.html", "structImVec2ih" ],
    [ "ImVec4", "structImVec4.html", "structImVec4" ],
    [ "ImVector", "structImVector.html", "structImVector" ],
    [ "IRenderPass", "classIRenderPass.html", "classIRenderPass" ],
    [ "ISelectable", "classISelectable.html", "classISelectable" ],
    [ "LoadedModelData", "structLoadedModelData.html", "structLoadedModelData" ],
    [ "Manager", "classManager.html", "classManager" ],
    [ "MaterialData", "structMaterialData.html", "structMaterialData" ],
    [ "MeshConstantBufferData", "structMeshConstantBufferData.html", "structMeshConstantBufferData" ],
    [ "MeshData", "structMeshData.html", "structMeshData" ],
    [ "MeshVertex", "structMeshVertex.html", "structMeshVertex" ],
    [ "ModelManager", "classModelManager.html", "classModelManager" ],
    [ "MyDocument", "structMyDocument.html", "structMyDocument" ],
    [ "NodeData", "structNodeData.html", "structNodeData" ],
    [ "ObjectManager", "classObjectManager.html", "classObjectManager" ],
    [ "Player", "classPlayer.html", "classPlayer" ],
    [ "PostProcessPass", "classPostProcessPass.html", "classPostProcessPass" ],
    [ "PSOBuilder", "classPSOBuilder.html", "classPSOBuilder" ],
    [ "PSOManager", "classPSOManager.html", "classPSOManager" ],
    [ "RandomParticle", "classRandomParticle.html", "classRandomParticle" ],
    [ "RenderContext", "structRenderContext.html", "structRenderContext" ],
    [ "RenderPipeline", "classRenderPipeline.html", "classRenderPipeline" ],
    [ "RenderTexture", "classRenderTexture.html", "classRenderTexture" ],
    [ "RootSignatureBuilder", "classRootSignatureBuilder.html", "classRootSignatureBuilder" ],
    [ "SceneManager", "classSceneManager.html", "classSceneManager" ],
    [ "SceneTitle", "classSceneTitle.html", "classSceneTitle" ],
    [ "Shader", "classShader.html", "classShader" ],
    [ "ShaderManager", "classShaderManager.html", "classShaderManager" ],
    [ "SkinData", "structSkinData.html", "structSkinData" ],
    [ "Skydome", "classSkydome.html", "classSkydome" ],
    [ "SpriteVertex", "structSpriteVertex.html", "structSpriteVertex" ],
    [ "STB_TexteditState", "structSTB__TexteditState.html", "structSTB__TexteditState" ],
    [ "stbi_io_callbacks", "structstbi__io__callbacks.html", "structstbi__io__callbacks" ],
    [ "stbrp_context", "structstbrp__context.html", "structstbrp__context" ],
    [ "stbrp_context_opaque", "structstbrp__context__opaque.html", "structstbrp__context__opaque" ],
    [ "stbrp_node", "structstbrp__node.html", "structstbrp__node" ],
    [ "stbrp_rect", "structstbrp__rect.html", "structstbrp__rect" ],
    [ "StbTexteditRow", "structStbTexteditRow.html", "structStbTexteditRow" ],
    [ "stbtt__bitmap", "structstbtt____bitmap.html", "structstbtt____bitmap" ],
    [ "stbtt__buf", "structstbtt____buf.html", "structstbtt____buf" ],
    [ "stbtt_aligned_quad", "structstbtt__aligned__quad.html", "structstbtt__aligned__quad" ],
    [ "stbtt_bakedchar", "structstbtt__bakedchar.html", "structstbtt__bakedchar" ],
    [ "stbtt_fontinfo", "structstbtt__fontinfo.html", "structstbtt__fontinfo" ],
    [ "stbtt_kerningentry", "structstbtt__kerningentry.html", "structstbtt__kerningentry" ],
    [ "stbtt_pack_context", "structstbtt__pack__context.html", "structstbtt__pack__context" ],
    [ "stbtt_pack_range", "structstbtt__pack__range.html", "structstbtt__pack__range" ],
    [ "stbtt_packedchar", "structstbtt__packedchar.html", "structstbtt__packedchar" ],
    [ "stbtt_vertex", "structstbtt__vertex.html", "structstbtt__vertex" ],
    [ "StbUndoRecord", "structStbUndoRecord.html", "structStbUndoRecord" ],
    [ "StbUndoState", "structStbUndoState.html", "structStbUndoState" ],
    [ "TextObject", "classTextObject.html", "classTextObject" ],
    [ "TextureManager", "classTextureManager.html", "classTextureManager" ],
    [ "tinygltf_json", "classtinygltf__json.html", "classtinygltf__json" ],
    [ "tinygltf_json_member", "structtinygltf__json__member.html", "structtinygltf__json__member" ],
    [ "TitleUI", "classTitleUI.html", "classTitleUI" ],
    [ "Vertex", "structVertex.html", "structVertex" ],
    [ "VERTEX_CONSTANT_BUFFER_DX12", "structVERTEX__CONSTANT__BUFFER__DX12.html", "structVERTEX__CONSTANT__BUFFER__DX12" ]
];