var hierarchy =
[
    [ "tinygltf::Accessor", "structtinygltf_1_1Accessor.html", null ],
    [ "nlohmann::adl_serializer< ValueType, typename >", "structnlohmann_1_1adl__serializer.html", null ],
    [ "tinygltf::Animation", "structtinygltf_1_1Animation.html", null ],
    [ "tinygltf::AnimationChannel", "structtinygltf_1_1AnimationChannel.html", null ],
    [ "AnimationChannelData", "structAnimationChannelData.html", null ],
    [ "AnimationData", "structAnimationData.html", null ],
    [ "tinygltf::AnimationSampler", "structtinygltf_1_1AnimationSampler.html", null ],
    [ "AnimationSamplerData", "structAnimationSamplerData.html", null ],
    [ "tinygltf::Asset", "structtinygltf_1_1Asset.html", null ],
    [ "tinygltf::AudioEmitter", "structtinygltf_1_1AudioEmitter.html", null ],
    [ "tinygltf::AudioSource", "structtinygltf_1_1AudioSource.html", null ],
    [ "B1", null, [
      [ "nlohmann::detail::conjunction< B1 >", "structnlohmann_1_1detail_1_1conjunction_3_01B1_01_4.html", null ]
    ] ],
    [ "nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >", "classnlohmann_1_1basic__json.html", null ],
    [ "nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >", "classnlohmann_1_1detail_1_1binary__reader.html", null ],
    [ "nlohmann::detail::binary_writer< BasicJsonType, CharType >", "classnlohmann_1_1detail_1_1binary__writer.html", null ],
    [ "BinaryType", null, [
      [ "nlohmann::byte_container_with_subtype< BinaryType >", "classnlohmann_1_1byte__container__with__subtype.html", null ]
    ] ],
    [ "nlohmann::detail::dtoa_impl::boundaries", "structnlohmann_1_1detail_1_1dtoa__impl_1_1boundaries.html", null ],
    [ "tinygltf::Buffer", "structtinygltf_1_1Buffer.html", null ],
    [ "tinygltf::BufferView", "structtinygltf_1_1BufferView.html", null ],
    [ "ButtonEventManager", "classButtonEventManager.html", null ],
    [ "nlohmann::detail::dtoa_impl::cached_power", "structnlohmann_1_1detail_1_1dtoa__impl_1_1cached__power.html", null ],
    [ "tinygltf::Camera", "structtinygltf_1_1Camera.html", null ],
    [ "CBone", "classCBone.html", null ],
    [ "CBox", "classCBox.html", null ],
    [ "CComponent", "classCComponent.html", [
      [ "Audio", "classAudio.html", null ],
      [ "CModel", "classCModel.html", null ],
      [ "CObjectInfo", "classCObjectInfo.html", null ],
      [ "CSpriteRenderer", "classCSpriteRenderer.html", null ],
      [ "CTextRenderer", "classCTextRenderer.html", null ],
      [ "CTransform", "classCTransform.html", null ],
      [ "Collider", "classCollider.html", [
        [ "Collider3D", "classCollider3D.html", [
          [ "BoxCollider3D", "classBoxCollider3D.html", null ]
        ] ]
      ] ]
    ] ],
    [ "CDescriptorHeapAllocator", "classCDescriptorHeapAllocator.html", null ],
    [ "CgltfLoader", "classCgltfLoader.html", null ],
    [ "CImGuiManager", "classCImGuiManager.html", null ],
    [ "CInputManager", "classCInputManager.html", null ],
    [ "CInspectorUI", "classCInspectorUI.html", null ],
    [ "cj_frame", "structcj__frame.html", null ],
    [ "tinygltf::detail::CJ_NoAllocator", "structtinygltf_1_1detail_1_1CJ__NoAllocator.html", null ],
    [ "cj_parse_ctx", "structcj__parse__ctx.html", null ],
    [ "cj_strbuf", "structcj__strbuf.html", null ],
    [ "CMaterial", "classCMaterial.html", null ],
    [ "CMesh", "classCMesh.html", null ],
    [ "CObject", "classCObject.html", [
      [ "C3D_Object", "classC3D__Object.html", [
        [ "BillBoard", "classBillBoard.html", [
          [ "Explosion", "classExplosion.html", null ],
          [ "RandomParticle", "classRandomParticle.html", null ]
        ] ],
        [ "Bullet", "classBullet.html", null ],
        [ "Camera", "classCamera.html", null ],
        [ "Enemy", "classEnemy.html", null ],
        [ "Player", "classPlayer.html", null ],
        [ "Skydome", "classSkydome.html", null ]
      ] ],
      [ "CUIObject", "classCUIObject.html", [
        [ "CUIButton", "classCUIButton.html", null ],
        [ "TitleUI", "classTitleUI.html", null ]
      ] ],
      [ "Manager", "classManager.html", [
        [ "EnemyCounter", "classEnemyCounter.html", null ]
      ] ],
      [ "TextObject", "classTextObject.html", [
        [ "EnemyCount", "classEnemyCount.html", null ]
      ] ]
    ] ],
    [ "Collision", "classCollision.html", null ],
    [ "ConstantBufferData", "structConstantBufferData.html", null ],
    [ "nlohmann::detail::container_input_adapter_factory_impl::container_input_adapter_factory< ContainerType, Enable >", "structnlohmann_1_1detail_1_1container__input__adapter__factory__impl_1_1container__input__adapter__factory.html", null ],
    [ "nlohmann::detail::container_input_adapter_factory_impl::container_input_adapter_factory< ContainerType, void_t< decltype(begin(std::declval< ContainerType >()), end(std::declval< ContainerType >()))> >", "structnlohmann_1_1detail_1_1container__input__adapter__factory__impl_1_1container__input__adapte602516bdb0b70b8ee5c6d4ff825368be.html", null ],
    [ "CScene", "classCScene.html", [
      [ "CSceneTest", "classCSceneTest.html", null ],
      [ "SceneTitle", "classSceneTitle.html", null ]
    ] ],
    [ "CTexture", "classCTexture.html", null ],
    [ "D2DTextRenderer", "classD2DTextRenderer.html", null ],
    [ "nlohmann::detail::detector< Default, AlwaysVoid, Op, Args >", "structnlohmann_1_1detail_1_1detector.html", null ],
    [ "nlohmann::detail::detector< Default, void_t< Op< Args... > >, Op, Args... >", "structnlohmann_1_1detail_1_1detector_3_01Default_00_01void__t_3_01Op_3_01Args_8_8_8_01_4_01_4_00_01Op_00_01Args_8_8_8_01_4.html", null ],
    [ "nlohmann::detail::dtoa_impl::diyfp", "structnlohmann_1_1detail_1_1dtoa__impl_1_1diyfp.html", null ],
    [ "DX12Manager", "classDX12Manager.html", null ],
    [ "Event", "classEvent.html", null ],
    [ "EventData", "classEventData.html", [
      [ "EventData_NextScene", "classEventData__NextScene.html", null ]
    ] ],
    [ "EventManager", "classEventManager.html", null ],
    [ "ExampleAppConsole", "structExampleAppConsole.html", null ],
    [ "ExampleAppDocuments", "structExampleAppDocuments.html", null ],
    [ "ExampleAppLog", "structExampleAppLog.html", null ],
    [ "ExampleAppPropertyEditor", "structExampleAppPropertyEditor.html", null ],
    [ "ExampleAsset", "structExampleAsset.html", null ],
    [ "ExampleAssetsBrowser", "structExampleAssetsBrowser.html", null ],
    [ "ExampleDualListBox", "structExampleDualListBox.html", null ],
    [ "ExampleMemberInfo", "structExampleMemberInfo.html", null ],
    [ "ExampleTreeNode", "structExampleTreeNode.html", null ],
    [ "std::exception", null, [
      [ "nlohmann::detail::exception", "classnlohmann_1_1detail_1_1exception.html", [
        [ "nlohmann::detail::invalid_iterator", "classnlohmann_1_1detail_1_1invalid__iterator.html", null ],
        [ "nlohmann::detail::other_error", "classnlohmann_1_1detail_1_1other__error.html", null ],
        [ "nlohmann::detail::out_of_range", "classnlohmann_1_1detail_1_1out__of__range.html", null ],
        [ "nlohmann::detail::parse_error", "classnlohmann_1_1detail_1_1parse__error.html", null ],
        [ "nlohmann::detail::type_error", "classnlohmann_1_1detail_1_1type__error.html", null ]
      ] ]
    ] ],
    [ "nlohmann::detail::utility_internal::Extend< Seq, SeqSize, Rem >", "structnlohmann_1_1detail_1_1utility__internal_1_1Extend.html", null ],
    [ "nlohmann::detail::utility_internal::Extend< integer_sequence< T, Ints... >, SeqSize, 0 >", "structnlohmann_1_1detail_1_1utility__internal_1_1Extend_3_01integer__sequence_3_01T_00_01Ints_8_453fbce128d545e87778192b2e607842.html", null ],
    [ "nlohmann::detail::utility_internal::Extend< integer_sequence< T, Ints... >, SeqSize, 1 >", "structnlohmann_1_1detail_1_1utility__internal_1_1Extend_3_01integer__sequence_3_01T_00_01Ints_8_011635d85b816e1c1a7e948fa832c519.html", null ],
    [ "nlohmann::detail::external_constructor< value_t >", "structnlohmann_1_1detail_1_1external__constructor.html", null ],
    [ "nlohmann::detail::external_constructor< value_t::array >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1array_01_4.html", null ],
    [ "nlohmann::detail::external_constructor< value_t::binary >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1binary_01_4.html", null ],
    [ "nlohmann::detail::external_constructor< value_t::boolean >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1boolean_01_4.html", null ],
    [ "nlohmann::detail::external_constructor< value_t::number_float >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__float_01_4.html", null ],
    [ "nlohmann::detail::external_constructor< value_t::number_integer >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__integer_01_4.html", null ],
    [ "nlohmann::detail::external_constructor< value_t::number_unsigned >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__unsigned_01_4.html", null ],
    [ "nlohmann::detail::external_constructor< value_t::object >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1object_01_4.html", null ],
    [ "nlohmann::detail::external_constructor< value_t::string >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1string_01_4.html", null ],
    [ "std::false_type", null, [
      [ "nlohmann::detail::has_from_json< BasicJsonType, T, typename >", "structnlohmann_1_1detail_1_1has__from__json.html", null ],
      [ "nlohmann::detail::has_non_default_from_json< BasicJsonType, T, typename >", "structnlohmann_1_1detail_1_1has__non__default__from__json.html", null ],
      [ "nlohmann::detail::has_to_json< BasicJsonType, T, typename >", "structnlohmann_1_1detail_1_1has__to__json.html", null ],
      [ "nlohmann::detail::is_basic_json< typename >", "structnlohmann_1_1detail_1_1is__basic__json.html", null ],
      [ "nlohmann::detail::is_compatible_array_type_impl< BasicJsonType, CompatibleArrayType, typename >", "structnlohmann_1_1detail_1_1is__compatible__array__type__impl.html", [
        [ "nlohmann::detail::is_compatible_array_type< BasicJsonType, CompatibleArrayType >", "structnlohmann_1_1detail_1_1is__compatible__array__type.html", null ]
      ] ],
      [ "nlohmann::detail::is_compatible_integer_type_impl< RealIntegerType, CompatibleNumberIntegerType, typename >", "structnlohmann_1_1detail_1_1is__compatible__integer__type__impl.html", [
        [ "nlohmann::detail::is_compatible_integer_type< RealIntegerType, CompatibleNumberIntegerType >", "structnlohmann_1_1detail_1_1is__compatible__integer__type.html", null ]
      ] ],
      [ "nlohmann::detail::is_compatible_object_type_impl< BasicJsonType, CompatibleObjectType, typename >", "structnlohmann_1_1detail_1_1is__compatible__object__type__impl.html", [
        [ "nlohmann::detail::is_compatible_object_type< BasicJsonType, CompatibleObjectType >", "structnlohmann_1_1detail_1_1is__compatible__object__type.html", null ]
      ] ],
      [ "nlohmann::detail::is_compatible_type_impl< BasicJsonType, CompatibleType, typename >", "structnlohmann_1_1detail_1_1is__compatible__type__impl.html", [
        [ "nlohmann::detail::is_compatible_type< BasicJsonType, CompatibleType >", "structnlohmann_1_1detail_1_1is__compatible__type.html", null ]
      ] ],
      [ "nlohmann::detail::is_complete_type< T, typename >", "structnlohmann_1_1detail_1_1is__complete__type.html", null ],
      [ "nlohmann::detail::is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, typename >", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl.html", [
        [ "nlohmann::detail::is_constructible_array_type< BasicJsonType, ConstructibleArrayType >", "structnlohmann_1_1detail_1_1is__constructible__array__type.html", null ]
      ] ],
      [ "nlohmann::detail::is_constructible_object_type_impl< BasicJsonType, ConstructibleObjectType, typename >", "structnlohmann_1_1detail_1_1is__constructible__object__type__impl.html", [
        [ "nlohmann::detail::is_constructible_object_type< BasicJsonType, ConstructibleObjectType >", "structnlohmann_1_1detail_1_1is__constructible__object__type.html", null ]
      ] ],
      [ "nlohmann::detail::is_constructible_tuple< T1, T2 >", "structnlohmann_1_1detail_1_1is__constructible__tuple.html", null ],
      [ "nlohmann::detail::is_iterator_traits< T, typename >", "structnlohmann_1_1detail_1_1is__iterator__traits.html", null ],
      [ "nlohmann::detail::is_json_ref< typename >", "structnlohmann_1_1detail_1_1is__json__ref.html", null ]
    ] ],
    [ "nlohmann::detail::file_input_adapter", "classnlohmann_1_1detail_1_1file__input__adapter.html", null ],
    [ "D2DTextRenderer::FrameResources", "structD2DTextRenderer_1_1FrameResources.html", null ],
    [ "nlohmann::detail::from_json_fn", "structnlohmann_1_1detail_1_1from__json__fn.html", null ],
    [ "tinygltf::FsCallbacks", "structtinygltf_1_1FsCallbacks.html", null ],
    [ "nlohmann::detail::utility_internal::Gen< T, N >", "structnlohmann_1_1detail_1_1utility__internal_1_1Gen.html", null ],
    [ "nlohmann::detail::utility_internal::Gen< T, 0 >", "structnlohmann_1_1detail_1_1utility__internal_1_1Gen_3_01T_00_010_01_4.html", null ],
    [ "nlohmann::detail::has_from_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "structnlohmann_1_1detail_1_1has__from__json_3_01BasicJsonType_00_01T_00_01enable__if__t_3_01_9is3ee028c64c76c768be45996bb13fc9c5.html", null ],
    [ "nlohmann::detail::has_non_default_from_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "structnlohmann_1_1detail_1_1has__non__default__from__json_3_01BasicJsonType_00_01T_00_01enable__b7a8cd863889b54d1139b207b4233111.html", null ],
    [ "nlohmann::detail::has_to_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "structnlohmann_1_1detail_1_1has__to__json_3_01BasicJsonType_00_01T_00_01enable__if__t_3_01_9is__4a8838c1c30336126696a126041e661c.html", null ],
    [ "std::hash< nlohmann::json >", "structstd_1_1hash_3_01nlohmann_1_1json_01_4.html", null ],
    [ "nlohmann::detail::identity_tag< T >", "structnlohmann_1_1detail_1_1identity__tag.html", null ],
    [ "tinygltf::Image", "structtinygltf_1_1Image.html", null ],
    [ "ImBitArray< BITCOUNT, OFFSET >", "structImBitArray.html", null ],
    [ "ImBitArray< ImGuiKey_NamedKey_COUNT, -ImGuiKey_NamedKey_BEGIN >", "structImBitArray.html", null ],
    [ "ImBitVector", "structImBitVector.html", null ],
    [ "ImChunkStream< T >", "structImChunkStream.html", null ],
    [ "ImChunkStream< ImGuiTableSettings >", "structImChunkStream.html", null ],
    [ "ImChunkStream< ImGuiWindowSettings >", "structImChunkStream.html", null ],
    [ "ImColor", "structImColor.html", null ],
    [ "ImDrawChannel", "structImDrawChannel.html", null ],
    [ "ImDrawCmd", "structImDrawCmd.html", null ],
    [ "ImDrawCmdHeader", "structImDrawCmdHeader.html", null ],
    [ "ImDrawData", "structImDrawData.html", null ],
    [ "ImDrawDataBuilder", "structImDrawDataBuilder.html", null ],
    [ "ImDrawList", "structImDrawList.html", null ],
    [ "ImDrawListSharedData", "structImDrawListSharedData.html", null ],
    [ "ImDrawListSplitter", "structImDrawListSplitter.html", null ],
    [ "ImDrawVert", "structImDrawVert.html", null ],
    [ "ImFont", "structImFont.html", null ],
    [ "ImFontAtlas", "structImFontAtlas.html", null ],
    [ "ImFontAtlasBuilder", "structImFontAtlasBuilder.html", null ],
    [ "ImFontAtlasPostProcessData", "structImFontAtlasPostProcessData.html", null ],
    [ "ImFontAtlasRect", "structImFontAtlasRect.html", null ],
    [ "ImFontAtlasRectEntry", "structImFontAtlasRectEntry.html", null ],
    [ "ImFontBaked", "structImFontBaked.html", null ],
    [ "ImFontConfig", "structImFontConfig.html", null ],
    [ "ImFontGlyph", "structImFontGlyph.html", null ],
    [ "ImFontGlyphRangesBuilder", "structImFontGlyphRangesBuilder.html", null ],
    [ "ImFontLoader", "structImFontLoader.html", null ],
    [ "ImFontStackData", "structImFontStackData.html", null ],
    [ "ImGui_ImplDX12_Data", "structImGui__ImplDX12__Data.html", null ],
    [ "ImGui_ImplDX12_InitInfo", "structImGui__ImplDX12__InitInfo.html", null ],
    [ "ImGui_ImplDX12_RenderBuffers", "structImGui__ImplDX12__RenderBuffers.html", null ],
    [ "ImGui_ImplDX12_RenderState", "structImGui__ImplDX12__RenderState.html", null ],
    [ "ImGui_ImplDX12_Texture", "structImGui__ImplDX12__Texture.html", null ],
    [ "ImGui_ImplStbTrueType_FontSrcData", "structImGui__ImplStbTrueType__FontSrcData.html", null ],
    [ "ImGui_ImplWin32_Data", "structImGui__ImplWin32__Data.html", null ],
    [ "ImGuiBoxSelectState", "structImGuiBoxSelectState.html", null ],
    [ "ImGuiColorMod", "structImGuiColorMod.html", null ],
    [ "ImGuiComboPreviewData", "structImGuiComboPreviewData.html", null ],
    [ "ImGuiContext", "structImGuiContext.html", null ],
    [ "ImGuiContextHook", "structImGuiContextHook.html", null ],
    [ "ImGuiDataTypeInfo", "structImGuiDataTypeInfo.html", null ],
    [ "ImGuiDataTypeStorage", "structImGuiDataTypeStorage.html", null ],
    [ "ImGuiDeactivatedItemData", "structImGuiDeactivatedItemData.html", null ],
    [ "ImGuiDebugAllocEntry", "structImGuiDebugAllocEntry.html", null ],
    [ "ImGuiDebugAllocInfo", "structImGuiDebugAllocInfo.html", null ],
    [ "ImGuiDebugItemPathQuery", "structImGuiDebugItemPathQuery.html", null ],
    [ "ImGuiDemoWindowData", "structImGuiDemoWindowData.html", null ],
    [ "ImGuiErrorRecoveryState", "structImGuiErrorRecoveryState.html", null ],
    [ "ImGuiFocusScopeData", "structImGuiFocusScopeData.html", null ],
    [ "ImGuiGroupData", "structImGuiGroupData.html", null ],
    [ "ImGuiIDStackTool", "structImGuiIDStackTool.html", null ],
    [ "ImGuiInputEvent", "structImGuiInputEvent.html", null ],
    [ "ImGuiInputEventAppFocused", "structImGuiInputEventAppFocused.html", null ],
    [ "ImGuiInputEventKey", "structImGuiInputEventKey.html", null ],
    [ "ImGuiInputEventMouseButton", "structImGuiInputEventMouseButton.html", null ],
    [ "ImGuiInputEventMousePos", "structImGuiInputEventMousePos.html", null ],
    [ "ImGuiInputEventMouseWheel", "structImGuiInputEventMouseWheel.html", null ],
    [ "ImGuiInputEventText", "structImGuiInputEventText.html", null ],
    [ "ImGuiInputTextCallbackData", "structImGuiInputTextCallbackData.html", null ],
    [ "ImGuiInputTextDeactivatedState", "structImGuiInputTextDeactivatedState.html", null ],
    [ "ImGuiInputTextState", "structImGuiInputTextState.html", null ],
    [ "ImGuiIO", "structImGuiIO.html", null ],
    [ "ImGuiKeyData", "structImGuiKeyData.html", null ],
    [ "ImGuiKeyOwnerData", "structImGuiKeyOwnerData.html", null ],
    [ "ImGuiKeyRoutingData", "structImGuiKeyRoutingData.html", null ],
    [ "ImGuiKeyRoutingTable", "structImGuiKeyRoutingTable.html", null ],
    [ "ImGuiLastItemData", "structImGuiLastItemData.html", null ],
    [ "ImGuiListClipper", "structImGuiListClipper.html", null ],
    [ "ImGuiListClipperData", "structImGuiListClipperData.html", null ],
    [ "ImGuiListClipperRange", "structImGuiListClipperRange.html", null ],
    [ "ImGuiLocEntry", "structImGuiLocEntry.html", null ],
    [ "ImGuiMenuColumns", "structImGuiMenuColumns.html", null ],
    [ "ImGuiMetricsConfig", "structImGuiMetricsConfig.html", null ],
    [ "ImGuiMultiSelectIO", "structImGuiMultiSelectIO.html", null ],
    [ "ImGuiMultiSelectState", "structImGuiMultiSelectState.html", null ],
    [ "ImGuiMultiSelectTempData", "structImGuiMultiSelectTempData.html", null ],
    [ "ImGuiNavItemData", "structImGuiNavItemData.html", null ],
    [ "ImGuiNextItemData", "structImGuiNextItemData.html", null ],
    [ "ImGuiNextWindowData", "structImGuiNextWindowData.html", null ],
    [ "ImGuiOldColumnData", "structImGuiOldColumnData.html", null ],
    [ "ImGuiOldColumns", "structImGuiOldColumns.html", null ],
    [ "ImGuiOnceUponAFrame", "structImGuiOnceUponAFrame.html", null ],
    [ "ImGuiPayload", "structImGuiPayload.html", null ],
    [ "ImGuiPlatformImeData", "structImGuiPlatformImeData.html", null ],
    [ "ImGuiPlatformIO", "structImGuiPlatformIO.html", null ],
    [ "ImGuiPlotArrayGetterData", "structImGuiPlotArrayGetterData.html", null ],
    [ "ImGuiPopupData", "structImGuiPopupData.html", null ],
    [ "ImGuiPtrOrIndex", "structImGuiPtrOrIndex.html", null ],
    [ "ImGuiResizeBorderDef", "structImGuiResizeBorderDef.html", null ],
    [ "ImGuiResizeGripDef", "structImGuiResizeGripDef.html", null ],
    [ "ImGuiSelectionBasicStorage", "structImGuiSelectionBasicStorage.html", [
      [ "ExampleSelectionWithDeletion", "structExampleSelectionWithDeletion.html", null ]
    ] ],
    [ "ImGuiSelectionExternalStorage", "structImGuiSelectionExternalStorage.html", null ],
    [ "ImGuiSelectionRequest", "structImGuiSelectionRequest.html", null ],
    [ "ImGuiSettingsHandler", "structImGuiSettingsHandler.html", null ],
    [ "ImGuiShrinkWidthItem", "structImGuiShrinkWidthItem.html", null ],
    [ "ImGuiSizeCallbackData", "structImGuiSizeCallbackData.html", null ],
    [ "ImGuiStackLevelInfo", "structImGuiStackLevelInfo.html", null ],
    [ "ImGuiStorage", "structImGuiStorage.html", null ],
    [ "ImGuiStoragePair", "structImGuiStoragePair.html", null ],
    [ "ImGuiStyle", "structImGuiStyle.html", null ],
    [ "ImGuiStyleMod", "structImGuiStyleMod.html", null ],
    [ "ImGuiStyleVarInfo", "structImGuiStyleVarInfo.html", null ],
    [ "ImGuiTabBar", "structImGuiTabBar.html", null ],
    [ "ImGuiTabBarSection", "structImGuiTabBarSection.html", null ],
    [ "ImGuiTabItem", "structImGuiTabItem.html", null ],
    [ "ImGuiTable", "structImGuiTable.html", null ],
    [ "ImGuiTableCellData", "structImGuiTableCellData.html", null ],
    [ "ImGuiTableColumn", "structImGuiTableColumn.html", null ],
    [ "ImGuiTableColumnSettings", "structImGuiTableColumnSettings.html", null ],
    [ "ImGuiTableColumnSortSpecs", "structImGuiTableColumnSortSpecs.html", null ],
    [ "ImGuiTableFixDisplayOrderColumnData", "structImGuiTableFixDisplayOrderColumnData.html", null ],
    [ "ImGuiTableHeaderData", "structImGuiTableHeaderData.html", null ],
    [ "ImGuiTableInstanceData", "structImGuiTableInstanceData.html", null ],
    [ "ImGuiTableSettings", "structImGuiTableSettings.html", null ],
    [ "ImGuiTableSortSpecs", "structImGuiTableSortSpecs.html", null ],
    [ "ImGuiTableTempData", "structImGuiTableTempData.html", null ],
    [ "ImGuiTextBuffer", "structImGuiTextBuffer.html", null ],
    [ "ImGuiTextFilter", "structImGuiTextFilter.html", null ],
    [ "ImGuiTextIndex", "structImGuiTextIndex.html", null ],
    [ "ImGuiTextFilter::ImGuiTextRange", "structImGuiTextFilter_1_1ImGuiTextRange.html", null ],
    [ "ImGuiTreeNodeStackData", "structImGuiTreeNodeStackData.html", null ],
    [ "ImGuiTypingSelectRequest", "structImGuiTypingSelectRequest.html", null ],
    [ "ImGuiTypingSelectState", "structImGuiTypingSelectState.html", null ],
    [ "ImGuiViewport", "structImGuiViewport.html", [
      [ "ImGuiViewportP", "structImGuiViewportP.html", null ]
    ] ],
    [ "ImGuiWindow", "structImGuiWindow.html", null ],
    [ "ImGuiWindowSettings", "structImGuiWindowSettings.html", null ],
    [ "ImGuiWindowStackData", "structImGuiWindowStackData.html", null ],
    [ "ImGuiWindowTempData", "structImGuiWindowTempData.html", null ],
    [ "ImNewWrapper", "structImNewWrapper.html", null ],
    [ "ImPool< T >", "structImPool.html", null ],
    [ "ImPool< ImGuiMultiSelectState >", "structImPool.html", null ],
    [ "ImPool< ImGuiTabBar >", "structImPool.html", null ],
    [ "ImPool< ImGuiTable >", "structImPool.html", null ],
    [ "ImRect", "structImRect.html", null ],
    [ "ImSpan< T >", "structImSpan.html", null ],
    [ "ImSpan< ImGuiTableCellData >", "structImSpan.html", null ],
    [ "ImSpan< ImGuiTableColumn >", "structImSpan.html", null ],
    [ "ImSpan< ImGuiTableColumnIdx >", "structImSpan.html", null ],
    [ "ImSpanAllocator< CHUNKS >", "structImSpanAllocator.html", null ],
    [ "ImStableVector< T, BLOCKSIZE >", "structImStableVector.html", null ],
    [ "ImStableVector< ImFontBaked, 32 >", "structImStableVector.html", null ],
    [ "ImTextureData", "structImTextureData.html", null ],
    [ "ImTextureRect", "structImTextureRect.html", null ],
    [ "ImTextureRef", "structImTextureRef.html", null ],
    [ "ImTriangulator", "structImTriangulator.html", null ],
    [ "ImTriangulatorNode", "structImTriangulatorNode.html", null ],
    [ "ImTriangulatorNodeSpan", "structImTriangulatorNodeSpan.html", null ],
    [ "ImVec1", "structImVec1.html", null ],
    [ "ImVec2", "structImVec2.html", null ],
    [ "ImVec2i", "structImVec2i.html", null ],
    [ "ImVec2ih", "structImVec2ih.html", null ],
    [ "ImVec4", "structImVec4.html", null ],
    [ "ImVector< T >", "structImVector.html", null ],
    [ "ImVector< char * >", "structImVector.html", null ],
    [ "ImVector< char >", "structImVector.html", null ],
    [ "ImVector< const char * >", "structImVector.html", null ],
    [ "ImVector< ExampleAsset >", "structImVector.html", null ],
    [ "ImVector< ExampleTreeNode * >", "structImVector.html", null ],
    [ "ImVector< float >", "structImVector.html", null ],
    [ "ImVector< ImDrawChannel >", "structImVector.html", null ],
    [ "ImVector< ImDrawCmd >", "structImVector.html", null ],
    [ "ImVector< ImDrawIdx >", "structImVector.html", null ],
    [ "ImVector< ImDrawList * >", "structImVector.html", null ],
    [ "ImVector< ImDrawListSharedData * >", "structImVector.html", null ],
    [ "ImVector< ImDrawVert >", "structImVector.html", null ],
    [ "ImVector< ImFont * >", "structImVector.html", null ],
    [ "ImVector< ImFontAtlas * >", "structImVector.html", null ],
    [ "ImVector< ImFontAtlasRectEntry >", "structImVector.html", null ],
    [ "ImVector< ImFontBaked * >", "structImVector.html", null ],
    [ "ImVector< ImFontConfig * >", "structImVector.html", null ],
    [ "ImVector< ImFontConfig >", "structImVector.html", null ],
    [ "ImVector< ImFontGlyph >", "structImVector.html", null ],
    [ "ImVector< ImFontStackData >", "structImVector.html", null ],
    [ "ImVector< ImGuiColorMod >", "structImVector.html", null ],
    [ "ImVector< ImGuiContextHook >", "structImVector.html", null ],
    [ "ImVector< ImGuiFocusScopeData >", "structImVector.html", null ],
    [ "ImVector< ImGuiGroupData >", "structImVector.html", null ],
    [ "ImVector< ImGuiID >", "structImVector.html", null ],
    [ "ImVector< ImGuiInputEvent >", "structImVector.html", null ],
    [ "ImVector< ImGuiItemFlags >", "structImVector.html", null ],
    [ "ImVector< ImGuiKeyRoutingData >", "structImVector.html", null ],
    [ "ImVector< ImGuiListClipperData >", "structImVector.html", null ],
    [ "ImVector< ImGuiListClipperRange >", "structImVector.html", null ],
    [ "ImVector< ImGuiMultiSelectState >", "structImVector.html", null ],
    [ "ImVector< ImGuiMultiSelectTempData >", "structImVector.html", null ],
    [ "ImVector< ImGuiOldColumnData >", "structImVector.html", null ],
    [ "ImVector< ImGuiOldColumns >", "structImVector.html", null ],
    [ "ImVector< ImGuiPopupData >", "structImVector.html", null ],
    [ "ImVector< ImGuiPtrOrIndex >", "structImVector.html", null ],
    [ "ImVector< ImGuiSelectionRequest >", "structImVector.html", null ],
    [ "ImVector< ImGuiSettingsHandler >", "structImVector.html", null ],
    [ "ImVector< ImGuiShrinkWidthItem >", "structImVector.html", null ],
    [ "ImVector< ImGuiStackLevelInfo >", "structImVector.html", null ],
    [ "ImVector< ImGuiStoragePair >", "structImVector.html", null ],
    [ "ImVector< ImGuiStyleMod >", "structImVector.html", null ],
    [ "ImVector< ImGuiTabBar >", "structImVector.html", null ],
    [ "ImVector< ImGuiTabItem >", "structImVector.html", null ],
    [ "ImVector< ImGuiTable >", "structImVector.html", null ],
    [ "ImVector< ImGuiTableColumnSortSpecs >", "structImVector.html", null ],
    [ "ImVector< ImGuiTableHeaderData >", "structImVector.html", null ],
    [ "ImVector< ImGuiTableInstanceData >", "structImVector.html", null ],
    [ "ImVector< ImGuiTableTempData >", "structImVector.html", null ],
    [ "ImVector< ImGuiTextFilter::ImGuiTextRange >", "structImVector.html", null ],
    [ "ImVector< ImGuiTreeNodeStackData >", "structImVector.html", null ],
    [ "ImVector< ImGuiViewportP * >", "structImVector.html", null ],
    [ "ImVector< ImGuiWindow * >", "structImVector.html", null ],
    [ "ImVector< ImGuiWindowStackData >", "structImVector.html", null ],
    [ "ImVector< ImTextureData * >", "structImVector.html", null ],
    [ "ImVector< ImTextureRect >", "structImVector.html", null ],
    [ "ImVector< ImTextureRef >", "structImVector.html", null ],
    [ "ImVector< ImU16 >", "structImVector.html", null ],
    [ "ImVector< ImU32 >", "structImVector.html", null ],
    [ "ImVector< ImU8 >", "structImVector.html", null ],
    [ "ImVector< ImVec2 >", "structImVector.html", null ],
    [ "ImVector< ImVec4 >", "structImVector.html", null ],
    [ "ImVector< ImWchar >", "structImVector.html", null ],
    [ "ImVector< int >", "structImVector.html", null ],
    [ "ImVector< MyDocument * >", "structImVector.html", null ],
    [ "ImVector< MyDocument >", "structImVector.html", null ],
    [ "ImVector< stbrp_node >", "structImVector.html", null ],
    [ "ImVector< T * >", "structImVector.html", null ],
    [ "ImVector< unsigned char >", "structImVector.html", null ],
    [ "nlohmann::detail::input_stream_adapter", "classnlohmann_1_1detail_1_1input__stream__adapter.html", null ],
    [ "nlohmann::detail::integer_sequence< T, Ints >", "structnlohmann_1_1detail_1_1integer__sequence.html", null ],
    [ "std::integral_constant", null, [
      [ "nlohmann::detail::negation< B >", "structnlohmann_1_1detail_1_1negation.html", null ],
      [ "std::tuple_size<::nlohmann::detail::iteration_proxy_value< IteratorType > >", "classstd_1_1tuple__size_3_1_1nlohmann_1_1detail_1_1iteration__proxy__value_3_01IteratorType_01_4_01_4.html", null ]
    ] ],
    [ "nlohmann::detail::internal_iterator< BasicJsonType >", "structnlohmann_1_1detail_1_1internal__iterator.html", null ],
    [ "nlohmann::detail::internal_iterator< typename std::remove_const< BasicJsonType >::type >", "structnlohmann_1_1detail_1_1internal__iterator.html", null ],
    [ "IRenderPass", "classIRenderPass.html", [
      [ "ForwardRenderPass", "classForwardRenderPass.html", null ],
      [ "PostProcessPass", "classPostProcessPass.html", null ]
    ] ],
    [ "nlohmann::detail::is_compatible_array_type_impl< BasicJsonType, CompatibleArrayType, enable_if_t< is_detected< iterator_t, CompatibleArrayType >::value &&is_iterator_traits< iterator_traits< detected_t< iterator_t, CompatibleArrayType > > >::value &&!std::is_same< CompatibleArrayType, detected_t< range_value_t, CompatibleArrayType > >::value > >", "structnlohmann_1_1detail_1_1is__compatible__array__type__impl_3_01BasicJsonType_00_01CompatibleAfaa3c0bd038fd031f5ee109e19639e03.html", null ],
    [ "nlohmann::detail::is_compatible_integer_type_impl< RealIntegerType, CompatibleNumberIntegerType, enable_if_t< std::is_integral< RealIntegerType >::value &&std::is_integral< CompatibleNumberIntegerType >::value &&!std::is_same< bool, CompatibleNumberIntegerType >::value > >", "structnlohmann_1_1detail_1_1is__compatible__integer__type__impl_3_01RealIntegerType_00_01Compatie5920c849e839ebb9f8c57349c900796.html", null ],
    [ "nlohmann::detail::is_compatible_object_type_impl< BasicJsonType, CompatibleObjectType, enable_if_t< is_detected< mapped_type_t, CompatibleObjectType >::value &&is_detected< key_type_t, CompatibleObjectType >::value > >", "structnlohmann_1_1detail_1_1is__compatible__object__type__impl_3_01BasicJsonType_00_01Compatible1dd1bd23ba0e4ce33237aa702f8058a9.html", null ],
    [ "nlohmann::detail::is_compatible_string_type< BasicJsonType, CompatibleStringType >", "structnlohmann_1_1detail_1_1is__compatible__string__type.html", null ],
    [ "nlohmann::detail::is_compatible_type_impl< BasicJsonType, CompatibleType, enable_if_t< is_complete_type< CompatibleType >::value > >", "structnlohmann_1_1detail_1_1is__compatible__type__impl_3_01BasicJsonType_00_01CompatibleType_00_fa54cb60e66f5c6ba93b1dd3f418b703.html", null ],
    [ "std::is_constructible", null, [
      [ "nlohmann::detail::is_constructible< T, Args >", "structnlohmann_1_1detail_1_1is__constructible.html", null ]
    ] ],
    [ "nlohmann::detail::is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< !std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value &&!is_compatible_string_type< BasicJsonType, ConstructibleArrayType >::value &&is_default_constructible< ConstructibleArrayType >::value &&(std::is_move_assignable< ConstructibleArrayType >::value||std::is_copy_assignable< ConstructibleArrayType >::value)&&is_detected< iterator_t, ConstructibleArrayType >::value &&is_iterator_traits< iterator_traits< detected_t< iterator_t, ConstructibleArrayType > > >::value &&is_detected< range_value_t, ConstructibleArrayType >::value &&!std::is_same< ConstructibleArrayType, detected_t< range_value_t, ConstructibleArrayType > >::value &&is_complete_type< detected_t< range_value_t, ConstructibleArrayType > >::value > >", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl_3_01BasicJsonType_00_01Construc9fb32d79d2f03f291695c23371cb431d.html", null ],
    [ "nlohmann::detail::is_constructible_object_type_impl< BasicJsonType, ConstructibleObjectType, enable_if_t< is_detected< mapped_type_t, ConstructibleObjectType >::value &&is_detected< key_type_t, ConstructibleObjectType >::value > >", "structnlohmann_1_1detail_1_1is__constructible__object__type__impl_3_01BasicJsonType_00_01Construa4d1e16800f2c4963485512ecf18377c.html", null ],
    [ "nlohmann::detail::is_constructible_string_type< BasicJsonType, ConstructibleStringType >", "structnlohmann_1_1detail_1_1is__constructible__string__type.html", null ],
    [ "std::is_default_constructible", null, [
      [ "nlohmann::detail::is_default_constructible< T >", "structnlohmann_1_1detail_1_1is__default__constructible.html", null ]
    ] ],
    [ "is_detected", null, [
      [ "nlohmann::detail::is_detected_lazy< Op, Args >", "structnlohmann_1_1detail_1_1is__detected__lazy.html", null ]
    ] ],
    [ "nlohmann::detail::is_getable< BasicJsonType, T >", "structnlohmann_1_1detail_1_1is__getable.html", null ],
    [ "nlohmann::detail::is_iterator_of_multibyte< T >", "structnlohmann_1_1detail_1_1is__iterator__of__multibyte.html", null ],
    [ "nlohmann::detail::is_iterator_traits< iterator_traits< T > >", "structnlohmann_1_1detail_1_1is__iterator__traits_3_01iterator__traits_3_01T_01_4_01_4.html", null ],
    [ "nlohmann::detail::is_ordered_map< T >", "structnlohmann_1_1detail_1_1is__ordered__map.html", null ],
    [ "nlohmann::detail::is_range< T >", "structnlohmann_1_1detail_1_1is__range.html", null ],
    [ "nlohmann::detail::is_sax< SAX, BasicJsonType >", "structnlohmann_1_1detail_1_1is__sax.html", null ],
    [ "nlohmann::detail::is_sax_static_asserts< SAX, BasicJsonType >", "structnlohmann_1_1detail_1_1is__sax__static__asserts.html", null ],
    [ "ISelectable", "classISelectable.html", [
      [ "CUIButton", "classCUIButton.html", null ]
    ] ],
    [ "nlohmann::detail::iter_impl< BasicJsonType >", "classnlohmann_1_1detail_1_1iter__impl.html", null ],
    [ "nlohmann::detail::iteration_proxy< IteratorType >", "classnlohmann_1_1detail_1_1iteration__proxy.html", null ],
    [ "nlohmann::detail::iteration_proxy_value< IteratorType >", "classnlohmann_1_1detail_1_1iteration__proxy__value.html", null ],
    [ "tinygltf_json::iterator", "classtinygltf__json_1_1iterator.html", null ],
    [ "nlohmann::detail::iterator_input_adapter< IteratorType >", "classnlohmann_1_1detail_1_1iterator__input__adapter.html", null ],
    [ "nlohmann::detail::iterator_input_adapter_factory< IteratorType, Enable >", "structnlohmann_1_1detail_1_1iterator__input__adapter__factory.html", null ],
    [ "nlohmann::detail::iterator_input_adapter_factory< IteratorType, enable_if_t< is_iterator_of_multibyte< IteratorType >::value > >", "structnlohmann_1_1detail_1_1iterator__input__adapter__factory_3_01IteratorType_00_01enable__if__0e86378a778d78dd2284e92dc30f4902.html", null ],
    [ "nlohmann::detail::iterator_traits< T, typename >", "structnlohmann_1_1detail_1_1iterator__traits.html", null ],
    [ "nlohmann::detail::iterator_traits< T *, enable_if_t< std::is_object< T >::value > >", "structnlohmann_1_1detail_1_1iterator__traits_3_01T_01_5_00_01enable__if__t_3_01std_1_1is__object_3_01T_01_4_1_1value_01_4_01_4.html", null ],
    [ "nlohmann::detail::iterator_types< It, typename >", "structnlohmann_1_1detail_1_1iterator__types.html", null ],
    [ "nlohmann::detail::iterator_types< It, void_t< typename It::difference_type, typename It::value_type, typename It::pointer, typename It::reference, typename It::iterator_category > >", "structnlohmann_1_1detail_1_1iterator__types_3_01It_00_01void__t_3_01typename_01It_1_1difference_d2be8685966c97e00e99d4fd2366dc0b.html", null ],
    [ "nlohmann::detail::iterator_types< T >", "structnlohmann_1_1detail_1_1iterator__types.html", [
      [ "nlohmann::detail::iterator_traits< T, enable_if_t< !std::is_pointer< T >::value > >", "structnlohmann_1_1detail_1_1iterator__traits_3_01T_00_01enable__if__t_3_01_9std_1_1is__pointer_3_01T_01_4_1_1value_01_4_01_4.html", null ]
    ] ],
    [ "nlohmann::json_pointer< BasicJsonType >", "classnlohmann_1_1json__pointer.html", null ],
    [ "nlohmann::detail::json_ref< BasicJsonType >", "classnlohmann_1_1detail_1_1json__ref.html", null ],
    [ "nlohmann::json_sax< BasicJsonType >", "structnlohmann_1_1json__sax.html", null ],
    [ "nlohmann::detail::json_sax_acceptor< BasicJsonType >", "classnlohmann_1_1detail_1_1json__sax__acceptor.html", null ],
    [ "nlohmann::detail::json_sax_dom_callback_parser< BasicJsonType >", "classnlohmann_1_1detail_1_1json__sax__dom__callback__parser.html", null ],
    [ "nlohmann::detail::json_sax_dom_parser< BasicJsonType >", "classnlohmann_1_1detail_1_1json__sax__dom__parser.html", null ],
    [ "std::less<::nlohmann::detail::value_t >", "structstd_1_1less_3_1_1nlohmann_1_1detail_1_1value__t_01_4.html", null ],
    [ "nlohmann::detail::lexer_base< BasicJsonType >", "classnlohmann_1_1detail_1_1lexer__base.html", [
      [ "nlohmann::detail::lexer< BasicJsonType, InputAdapterType >", "classnlohmann_1_1detail_1_1lexer.html", null ]
    ] ],
    [ "tinygltf::Light", "structtinygltf_1_1Light.html", null ],
    [ "LoadedModelData", "structLoadedModelData.html", null ],
    [ "nlohmann::detail::make_void< Ts >", "structnlohmann_1_1detail_1_1make__void.html", null ],
    [ "tinygltf::Material", "structtinygltf_1_1Material.html", null ],
    [ "MaterialData", "structMaterialData.html", null ],
    [ "tinygltf::Mesh", "structtinygltf_1_1Mesh.html", null ],
    [ "MeshConstantBufferData", "structMeshConstantBufferData.html", null ],
    [ "MeshData", "structMeshData.html", null ],
    [ "MeshVertex", "structMeshVertex.html", null ],
    [ "tinygltf::Model", "classtinygltf_1_1Model.html", null ],
    [ "ModelManager", "classModelManager.html", null ],
    [ "MyDocument", "structMyDocument.html", null ],
    [ "tinygltf::Node", "classtinygltf_1_1Node.html", null ],
    [ "NodeData", "structNodeData.html", null ],
    [ "nlohmann::detail::nonesuch", "structnlohmann_1_1detail_1_1nonesuch.html", null ],
    [ "tinygltf::NormalTextureInfo", "structtinygltf_1_1NormalTextureInfo.html", null ],
    [ "ObjectManager", "classObjectManager.html", null ],
    [ "tinygltf::OcclusionTextureInfo", "structtinygltf_1_1OcclusionTextureInfo.html", null ],
    [ "tinygltf::OrthographicCamera", "structtinygltf_1_1OrthographicCamera.html", null ],
    [ "nlohmann::detail::output_adapter< CharType, StringType >", "classnlohmann_1_1detail_1_1output__adapter.html", null ],
    [ "nlohmann::detail::output_adapter_protocol< CharType >", "structnlohmann_1_1detail_1_1output__adapter__protocol.html", [
      [ "nlohmann::detail::output_stream_adapter< CharType >", "classnlohmann_1_1detail_1_1output__stream__adapter.html", null ],
      [ "nlohmann::detail::output_string_adapter< CharType, StringType >", "classnlohmann_1_1detail_1_1output__string__adapter.html", null ],
      [ "nlohmann::detail::output_vector_adapter< CharType, AllocatorType >", "classnlohmann_1_1detail_1_1output__vector__adapter.html", null ]
    ] ],
    [ "tinygltf::Parameter", "structtinygltf_1_1Parameter.html", null ],
    [ "nlohmann::detail::parser< BasicJsonType, InputAdapterType >", "classnlohmann_1_1detail_1_1parser.html", null ],
    [ "tinygltf::PbrMetallicRoughness", "structtinygltf_1_1PbrMetallicRoughness.html", null ],
    [ "tinygltf::PerspectiveCamera", "structtinygltf_1_1PerspectiveCamera.html", null ],
    [ "nlohmann::detail::position_t", "structnlohmann_1_1detail_1_1position__t.html", null ],
    [ "tinygltf::PositionalEmitter", "structtinygltf_1_1PositionalEmitter.html", null ],
    [ "tinygltf::Primitive", "structtinygltf_1_1Primitive.html", null ],
    [ "nlohmann::detail::primitive_iterator_t", "classnlohmann_1_1detail_1_1primitive__iterator__t.html", null ],
    [ "nlohmann::detail::priority_tag< N >", "structnlohmann_1_1detail_1_1priority__tag.html", null ],
    [ "nlohmann::detail::priority_tag< 0 >", "structnlohmann_1_1detail_1_1priority__tag_3_010_01_4.html", null ],
    [ "PSOBuilder", "classPSOBuilder.html", null ],
    [ "PSOManager", "classPSOManager.html", null ],
    [ "RenderContext", "structRenderContext.html", null ],
    [ "RenderPipeline", "classRenderPipeline.html", null ],
    [ "RenderTexture", "classRenderTexture.html", null ],
    [ "std::reverse_iterator", null, [
      [ "nlohmann::detail::json_reverse_iterator< Base >", "classnlohmann_1_1detail_1_1json__reverse__iterator.html", null ]
    ] ],
    [ "RootSignatureBuilder", "classRootSignatureBuilder.html", null ],
    [ "tinygltf::Sampler", "structtinygltf_1_1Sampler.html", null ],
    [ "tinygltf::Scene", "structtinygltf_1_1Scene.html", null ],
    [ "SceneManager", "classSceneManager.html", null ],
    [ "nlohmann::detail::serializer< BasicJsonType >", "classnlohmann_1_1detail_1_1serializer.html", null ],
    [ "Shader", "classShader.html", null ],
    [ "ShaderManager", "classShaderManager.html", null ],
    [ "tinygltf::Skin", "structtinygltf_1_1Skin.html", null ],
    [ "SkinData", "structSkinData.html", null ],
    [ "nlohmann::detail::span_input_adapter", "classnlohmann_1_1detail_1_1span__input__adapter.html", null ],
    [ "tinygltf::Accessor::Sparse", "structtinygltf_1_1Accessor_1_1Sparse.html", null ],
    [ "tinygltf::SpotLight", "structtinygltf_1_1SpotLight.html", null ],
    [ "SpriteVertex", "structSpriteVertex.html", null ],
    [ "CImGuiManager::SrvAllocUserData", "structCImGuiManager_1_1SrvAllocUserData.html", null ],
    [ "nlohmann::detail::static_const< T >", "structnlohmann_1_1detail_1_1static__const.html", null ],
    [ "STB_TexteditState", "structSTB__TexteditState.html", null ],
    [ "stbi_io_callbacks", "structstbi__io__callbacks.html", null ],
    [ "stbrp_context", "structstbrp__context.html", null ],
    [ "stbrp_context_opaque", "structstbrp__context__opaque.html", null ],
    [ "stbrp_node", "structstbrp__node.html", null ],
    [ "stbrp_rect", "structstbrp__rect.html", null ],
    [ "StbTexteditRow", "structStbTexteditRow.html", null ],
    [ "stbtt__bitmap", "structstbtt____bitmap.html", null ],
    [ "stbtt__buf", "structstbtt____buf.html", null ],
    [ "stbtt_aligned_quad", "structstbtt__aligned__quad.html", null ],
    [ "stbtt_bakedchar", "structstbtt__bakedchar.html", null ],
    [ "stbtt_fontinfo", "structstbtt__fontinfo.html", null ],
    [ "stbtt_kerningentry", "structstbtt__kerningentry.html", null ],
    [ "stbtt_pack_context", "structstbtt__pack__context.html", null ],
    [ "stbtt_pack_range", "structstbtt__pack__range.html", null ],
    [ "stbtt_packedchar", "structstbtt__packedchar.html", null ],
    [ "stbtt_vertex", "structstbtt__vertex.html", null ],
    [ "StbUndoRecord", "structStbUndoRecord.html", null ],
    [ "StbUndoState", "structStbUndoState.html", null ],
    [ "D2DTextRenderer::TextInfo", "structD2DTextRenderer_1_1TextInfo.html", null ],
    [ "tinygltf::Texture", "structtinygltf_1_1Texture.html", null ],
    [ "tinygltf::TextureInfo", "structtinygltf_1_1TextureInfo.html", null ],
    [ "TextureManager", "classTextureManager.html", null ],
    [ "tinygltf::TinyGLTF", "classtinygltf_1_1TinyGLTF.html", null ],
    [ "tinygltf_json", "classtinygltf__json.html", null ],
    [ "tinygltf_json_member", "structtinygltf__json__member.html", null ],
    [ "nlohmann::detail::to_json_fn", "structnlohmann_1_1detail_1_1to__json__fn.html", null ],
    [ "std::true_type", null, [
      [ "nlohmann::detail::conjunction< is_constructible< T1, Args >... >", "structnlohmann_1_1detail_1_1conjunction.html", [
        [ "nlohmann::detail::is_constructible_tuple< T1, std::tuple< Args... > >", "structnlohmann_1_1detail_1_1is__constructible__tuple_3_01T1_00_01std_1_1tuple_3_01Args_8_8_8_01_4_01_4.html", null ]
      ] ],
      [ "nlohmann::detail::conjunction< is_default_constructible< T1 >, is_default_constructible< T2 > >", "structnlohmann_1_1detail_1_1conjunction.html", [
        [ "nlohmann::detail::is_default_constructible< const std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01const_01std_1_1pair_3_01T1_00_01T2_01_4_01_4.html", [
          [ "nlohmann::detail::is_constructible< const std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__constructible_3_01const_01std_1_1pair_3_01T1_00_01T2_01_4_01_4.html", null ]
        ] ],
        [ "nlohmann::detail::is_default_constructible< std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01std_1_1pair_3_01T1_00_01T2_01_4_01_4.html", [
          [ "nlohmann::detail::is_constructible< std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__constructible_3_01std_1_1pair_3_01T1_00_01T2_01_4_01_4.html", null ]
        ] ]
      ] ],
      [ "nlohmann::detail::conjunction< is_default_constructible< Ts >... >", "structnlohmann_1_1detail_1_1conjunction.html", [
        [ "nlohmann::detail::is_default_constructible< const std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01const_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", [
          [ "nlohmann::detail::is_constructible< const std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__constructible_3_01const_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", null ]
        ] ],
        [ "nlohmann::detail::is_default_constructible< std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", [
          [ "nlohmann::detail::is_constructible< std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__constructible_3_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", null ]
        ] ]
      ] ],
      [ "nlohmann::detail::conjunction<... >", "structnlohmann_1_1detail_1_1conjunction.html", null ],
      [ "nlohmann::detail::is_basic_json< NLOHMANN_BASIC_JSON_TPL >", "structnlohmann_1_1detail_1_1is__basic__json_3_01NLOHMANN__BASIC__JSON__TPL_01_4.html", null ],
      [ "nlohmann::detail::is_complete_type< T, decltype(void(sizeof(T)))>", "structnlohmann_1_1detail_1_1is__complete__type_3_01T_00_01decltype_07void_07sizeof_07T_08_08_08_4.html", null ],
      [ "nlohmann::detail::is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value > >", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl_3_01BasicJsonType_00_01Construce6fa33688da703b95649da4749cdeb98.html", null ],
      [ "nlohmann::detail::is_json_ref< json_ref< T > >", "structnlohmann_1_1detail_1_1is__json__ref_3_01json__ref_3_01T_01_4_01_4.html", null ]
    ] ],
    [ "std::tuple_element< N, ::nlohmann::detail::iteration_proxy_value< IteratorType > >", "classstd_1_1tuple__element_3_01N_00_01_1_1nlohmann_1_1detail_1_1iteration__proxy__value_3_01IteratorType_01_4_01_4.html", null ],
    [ "nlohmann::detail::is_ordered_map< T >::two", "structnlohmann_1_1detail_1_1is__ordered__map_1_1two.html", null ],
    [ "std::conditional::type", null, [
      [ "nlohmann::detail::conjunction< B1, Bn... >", "structnlohmann_1_1detail_1_1conjunction_3_01B1_00_01Bn_8_8_8_01_4.html", null ]
    ] ],
    [ "tinygltf::URICallbacks", "structtinygltf_1_1URICallbacks.html", null ],
    [ "tinygltf::Value", "classtinygltf_1_1Value.html", null ],
    [ "std::vector< std::pair< const Key, T >, std::allocator< std::pair< const Key, T > > >", null, [
      [ "nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >", "structnlohmann_1_1ordered__map.html", null ]
    ] ],
    [ "Vertex", "structVertex.html", null ],
    [ "VERTEX_CONSTANT_BUFFER_DX12", "structVERTEX__CONSTANT__BUFFER__DX12.html", null ],
    [ "nlohmann::detail::wide_string_input_adapter< BaseInputAdapter, WideCharType >", "classnlohmann_1_1detail_1_1wide__string__input__adapter.html", null ],
    [ "nlohmann::detail::wide_string_input_helper< BaseInputAdapter, T >", "structnlohmann_1_1detail_1_1wide__string__input__helper.html", null ],
    [ "nlohmann::detail::wide_string_input_helper< BaseInputAdapter, 2 >", "structnlohmann_1_1detail_1_1wide__string__input__helper_3_01BaseInputAdapter_00_012_01_4.html", null ],
    [ "nlohmann::detail::wide_string_input_helper< BaseInputAdapter, 4 >", "structnlohmann_1_1detail_1_1wide__string__input__helper_3_01BaseInputAdapter_00_014_01_4.html", null ]
];